package com.meidusa.demo.dal.model;

import com.meidusa.toolkit.dal.ibator.AbstractModel;
import java.util.Date;

public class EnterpriseInfo extends AbstractModel {
    /**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.id
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String id;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.name
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String name;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.registerTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date registertime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.registerAddr
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String registeraddr;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.registerCapital
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer registercapital;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.natureId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String natureid;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.officeAddr
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String officeaddr;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productbound;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.projectBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String projectbound;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industrybound;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.operationMode
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String operationmode;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.legalRepresentative
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String legalrepresentative;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.address
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String address;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.zip
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String zip;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.phone
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String phone;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.fax
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String fax;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.mobilePhone
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String mobilephone;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.url
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String url;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.employeeTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer employeetotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.managerTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer managertotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.techniciansTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer technicianstotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.bachelorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer bachelortotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.seniorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer seniortotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.middleTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer middletotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.juniorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer juniortotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.professionalTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Integer professionaltotal;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.IPOFlag
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String ipoflag;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.IPOTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date ipotime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.IPOArea
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String ipoarea;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.IPOForum
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String ipoforum;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.memberTypeId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String membertypeid;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.userLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String userloginid;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.password
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String password;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.feePaymentFlag
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String feepaymentflag;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.sponsorshipAmount
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Double sponsorshipamount;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.offersBeginTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date offersbegintime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.offersEndTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date offersendtime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.enrollTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date enrolltime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.withDrawtime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date withdrawtime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.lastUpdateLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String lastupdateloginid;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.lastUpdateDatetime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date lastupdatedatetime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.createdLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String createdloginid;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.createdDatetime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Date createddatetime;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.email
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String email;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.natureOtherDesc
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String natureotherdesc;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.legalRepresentativeTele
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String legalrepresentativetele;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.legalRepresentativeMobile
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String legalrepresentativemobile;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.linkMan
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String linkman;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.spQualifacationLevel
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String spqualifacationlevel;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualityCertifacation
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualitycertifacation;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualityCertifacationOtherDesc
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualitycertifacationotherdesc;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.toHighApplyLevel
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String tohighapplylevel;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMProdProd
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omprodprod;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMProdSale
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omprodsale;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMProjMaint
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omprojmaint;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMNetAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omnetalarm;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMspTain
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omsptain;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMMedia
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String ommedia;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMProjConstruct
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omprojconstruct;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.OMOther
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String omother;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualifacationGetFire
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualifacationgetfire;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualifacationGetConf
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualifacationgetconf;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualifacationGetBuildInte
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualifacationgetbuildinte;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualifacationGetBuildProj
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualifacationgetbuildproj;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualifacationGetITInte
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualifacationgetitinte;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundVideo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundvideo;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundBangSec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundbangsec;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundAroundAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundaroundalarm;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundTheftAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundtheftalarm;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundEntranceControl
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundentrancecontrol;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundBuildVoice
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundbuildvoice;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundBuildIntell
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundbuildintell;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundVohileAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundvohilealarm;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundBodySec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundbodysec;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundBaseSec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productboundbasesec;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.productBoundDoorAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String productbounddooralarm;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundFiance
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundfiance;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundCulture
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundculture;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundEducation
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundeducation;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundCommu
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundcommu;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundGov
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundgov;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundEnterprise
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundenterprise;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundEnerge
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundenerge;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.industryBoundHome
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String industryboundhome;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.totalAssets
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Double totalassets;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.businessIncome
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Double businessincome;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.netProfit
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private Double netprofit;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualificationSupervision
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualificationsupervision;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.qualificationComputerSp
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String qualificationcomputersp;
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds to the database column enterpriseinfo.introduction
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	private String introduction;


	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.id
	 * @return  the value of enterpriseinfo.id
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.id
	 * @param id  the value for enterpriseinfo.id
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.name
	 * @return  the value of enterpriseinfo.name
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.name
	 * @param name  the value for enterpriseinfo.name
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.registerTime
	 * @return  the value of enterpriseinfo.registerTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getRegistertime() {
		return registertime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.registerTime
	 * @param registertime  the value for enterpriseinfo.registerTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setRegistertime(Date registertime) {
		this.registertime = registertime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.registerAddr
	 * @return  the value of enterpriseinfo.registerAddr
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getRegisteraddr() {
		return registeraddr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.registerAddr
	 * @param registeraddr  the value for enterpriseinfo.registerAddr
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setRegisteraddr(String registeraddr) {
		this.registeraddr = registeraddr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.registerCapital
	 * @return  the value of enterpriseinfo.registerCapital
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getRegistercapital() {
		return registercapital;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.registerCapital
	 * @param registercapital  the value for enterpriseinfo.registerCapital
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setRegistercapital(Integer registercapital) {
		this.registercapital = registercapital;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.natureId
	 * @return  the value of enterpriseinfo.natureId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getNatureid() {
		return natureid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.natureId
	 * @param natureid  the value for enterpriseinfo.natureId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setNatureid(String natureid) {
		this.natureid = natureid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.officeAddr
	 * @return  the value of enterpriseinfo.officeAddr
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOfficeaddr() {
		return officeaddr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.officeAddr
	 * @param officeaddr  the value for enterpriseinfo.officeAddr
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOfficeaddr(String officeaddr) {
		this.officeaddr = officeaddr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBound
	 * @return  the value of enterpriseinfo.productBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductbound() {
		return productbound;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBound
	 * @param productbound  the value for enterpriseinfo.productBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductbound(String productbound) {
		this.productbound = productbound;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.projectBound
	 * @return  the value of enterpriseinfo.projectBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProjectbound() {
		return projectbound;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.projectBound
	 * @param projectbound  the value for enterpriseinfo.projectBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProjectbound(String projectbound) {
		this.projectbound = projectbound;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBound
	 * @return  the value of enterpriseinfo.industryBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustrybound() {
		return industrybound;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBound
	 * @param industrybound  the value for enterpriseinfo.industryBound
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustrybound(String industrybound) {
		this.industrybound = industrybound;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.operationMode
	 * @return  the value of enterpriseinfo.operationMode
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOperationmode() {
		return operationmode;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.operationMode
	 * @param operationmode  the value for enterpriseinfo.operationMode
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOperationmode(String operationmode) {
		this.operationmode = operationmode;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.legalRepresentative
	 * @return  the value of enterpriseinfo.legalRepresentative
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getLegalrepresentative() {
		return legalrepresentative;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.legalRepresentative
	 * @param legalrepresentative  the value for enterpriseinfo.legalRepresentative
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setLegalrepresentative(String legalrepresentative) {
		this.legalrepresentative = legalrepresentative;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.address
	 * @return  the value of enterpriseinfo.address
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.address
	 * @param address  the value for enterpriseinfo.address
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.zip
	 * @return  the value of enterpriseinfo.zip
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getZip() {
		return zip;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.zip
	 * @param zip  the value for enterpriseinfo.zip
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setZip(String zip) {
		this.zip = zip;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.phone
	 * @return  the value of enterpriseinfo.phone
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.phone
	 * @param phone  the value for enterpriseinfo.phone
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.fax
	 * @return  the value of enterpriseinfo.fax
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getFax() {
		return fax;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.fax
	 * @param fax  the value for enterpriseinfo.fax
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setFax(String fax) {
		this.fax = fax;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.mobilePhone
	 * @return  the value of enterpriseinfo.mobilePhone
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getMobilephone() {
		return mobilephone;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.mobilePhone
	 * @param mobilephone  the value for enterpriseinfo.mobilePhone
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setMobilephone(String mobilephone) {
		this.mobilephone = mobilephone;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.url
	 * @return  the value of enterpriseinfo.url
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.url
	 * @param url  the value for enterpriseinfo.url
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.employeeTotal
	 * @return  the value of enterpriseinfo.employeeTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getEmployeetotal() {
		return employeetotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.employeeTotal
	 * @param employeetotal  the value for enterpriseinfo.employeeTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setEmployeetotal(Integer employeetotal) {
		this.employeetotal = employeetotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.managerTotal
	 * @return  the value of enterpriseinfo.managerTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getManagertotal() {
		return managertotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.managerTotal
	 * @param managertotal  the value for enterpriseinfo.managerTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setManagertotal(Integer managertotal) {
		this.managertotal = managertotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.techniciansTotal
	 * @return  the value of enterpriseinfo.techniciansTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getTechnicianstotal() {
		return technicianstotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.techniciansTotal
	 * @param technicianstotal  the value for enterpriseinfo.techniciansTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setTechnicianstotal(Integer technicianstotal) {
		this.technicianstotal = technicianstotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.bachelorTotal
	 * @return  the value of enterpriseinfo.bachelorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getBachelortotal() {
		return bachelortotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.bachelorTotal
	 * @param bachelortotal  the value for enterpriseinfo.bachelorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setBachelortotal(Integer bachelortotal) {
		this.bachelortotal = bachelortotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.seniorTotal
	 * @return  the value of enterpriseinfo.seniorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getSeniortotal() {
		return seniortotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.seniorTotal
	 * @param seniortotal  the value for enterpriseinfo.seniorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setSeniortotal(Integer seniortotal) {
		this.seniortotal = seniortotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.middleTotal
	 * @return  the value of enterpriseinfo.middleTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getMiddletotal() {
		return middletotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.middleTotal
	 * @param middletotal  the value for enterpriseinfo.middleTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setMiddletotal(Integer middletotal) {
		this.middletotal = middletotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.juniorTotal
	 * @return  the value of enterpriseinfo.juniorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getJuniortotal() {
		return juniortotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.juniorTotal
	 * @param juniortotal  the value for enterpriseinfo.juniorTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setJuniortotal(Integer juniortotal) {
		this.juniortotal = juniortotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.professionalTotal
	 * @return  the value of enterpriseinfo.professionalTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Integer getProfessionaltotal() {
		return professionaltotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.professionalTotal
	 * @param professionaltotal  the value for enterpriseinfo.professionalTotal
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProfessionaltotal(Integer professionaltotal) {
		this.professionaltotal = professionaltotal;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.IPOFlag
	 * @return  the value of enterpriseinfo.IPOFlag
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIpoflag() {
		return ipoflag;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.IPOFlag
	 * @param ipoflag  the value for enterpriseinfo.IPOFlag
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIpoflag(String ipoflag) {
		this.ipoflag = ipoflag;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.IPOTime
	 * @return  the value of enterpriseinfo.IPOTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getIpotime() {
		return ipotime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.IPOTime
	 * @param ipotime  the value for enterpriseinfo.IPOTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIpotime(Date ipotime) {
		this.ipotime = ipotime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.IPOArea
	 * @return  the value of enterpriseinfo.IPOArea
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIpoarea() {
		return ipoarea;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.IPOArea
	 * @param ipoarea  the value for enterpriseinfo.IPOArea
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIpoarea(String ipoarea) {
		this.ipoarea = ipoarea;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.IPOForum
	 * @return  the value of enterpriseinfo.IPOForum
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIpoforum() {
		return ipoforum;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.IPOForum
	 * @param ipoforum  the value for enterpriseinfo.IPOForum
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIpoforum(String ipoforum) {
		this.ipoforum = ipoforum;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.memberTypeId
	 * @return  the value of enterpriseinfo.memberTypeId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getMembertypeid() {
		return membertypeid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.memberTypeId
	 * @param membertypeid  the value for enterpriseinfo.memberTypeId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setMembertypeid(String membertypeid) {
		this.membertypeid = membertypeid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.userLoginId
	 * @return  the value of enterpriseinfo.userLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getUserloginid() {
		return userloginid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.userLoginId
	 * @param userloginid  the value for enterpriseinfo.userLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setUserloginid(String userloginid) {
		this.userloginid = userloginid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.password
	 * @return  the value of enterpriseinfo.password
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.password
	 * @param password  the value for enterpriseinfo.password
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.feePaymentFlag
	 * @return  the value of enterpriseinfo.feePaymentFlag
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getFeepaymentflag() {
		return feepaymentflag;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.feePaymentFlag
	 * @param feepaymentflag  the value for enterpriseinfo.feePaymentFlag
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setFeepaymentflag(String feepaymentflag) {
		this.feepaymentflag = feepaymentflag;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.sponsorshipAmount
	 * @return  the value of enterpriseinfo.sponsorshipAmount
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Double getSponsorshipamount() {
		return sponsorshipamount;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.sponsorshipAmount
	 * @param sponsorshipamount  the value for enterpriseinfo.sponsorshipAmount
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setSponsorshipamount(Double sponsorshipamount) {
		this.sponsorshipamount = sponsorshipamount;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.offersBeginTime
	 * @return  the value of enterpriseinfo.offersBeginTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getOffersbegintime() {
		return offersbegintime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.offersBeginTime
	 * @param offersbegintime  the value for enterpriseinfo.offersBeginTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOffersbegintime(Date offersbegintime) {
		this.offersbegintime = offersbegintime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.offersEndTime
	 * @return  the value of enterpriseinfo.offersEndTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getOffersendtime() {
		return offersendtime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.offersEndTime
	 * @param offersendtime  the value for enterpriseinfo.offersEndTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOffersendtime(Date offersendtime) {
		this.offersendtime = offersendtime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.enrollTime
	 * @return  the value of enterpriseinfo.enrollTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getEnrolltime() {
		return enrolltime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.enrollTime
	 * @param enrolltime  the value for enterpriseinfo.enrollTime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setEnrolltime(Date enrolltime) {
		this.enrolltime = enrolltime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.withDrawtime
	 * @return  the value of enterpriseinfo.withDrawtime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getWithdrawtime() {
		return withdrawtime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.withDrawtime
	 * @param withdrawtime  the value for enterpriseinfo.withDrawtime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setWithdrawtime(Date withdrawtime) {
		this.withdrawtime = withdrawtime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.lastUpdateLoginId
	 * @return  the value of enterpriseinfo.lastUpdateLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getLastupdateloginid() {
		return lastupdateloginid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.lastUpdateLoginId
	 * @param lastupdateloginid  the value for enterpriseinfo.lastUpdateLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setLastupdateloginid(String lastupdateloginid) {
		this.lastupdateloginid = lastupdateloginid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.lastUpdateDatetime
	 * @return  the value of enterpriseinfo.lastUpdateDatetime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getLastupdatedatetime() {
		return lastupdatedatetime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.lastUpdateDatetime
	 * @param lastupdatedatetime  the value for enterpriseinfo.lastUpdateDatetime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setLastupdatedatetime(Date lastupdatedatetime) {
		this.lastupdatedatetime = lastupdatedatetime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.createdLoginId
	 * @return  the value of enterpriseinfo.createdLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getCreatedloginid() {
		return createdloginid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.createdLoginId
	 * @param createdloginid  the value for enterpriseinfo.createdLoginId
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setCreatedloginid(String createdloginid) {
		this.createdloginid = createdloginid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.createdDatetime
	 * @return  the value of enterpriseinfo.createdDatetime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Date getCreateddatetime() {
		return createddatetime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.createdDatetime
	 * @param createddatetime  the value for enterpriseinfo.createdDatetime
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setCreateddatetime(Date createddatetime) {
		this.createddatetime = createddatetime;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.email
	 * @return  the value of enterpriseinfo.email
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.email
	 * @param email  the value for enterpriseinfo.email
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.natureOtherDesc
	 * @return  the value of enterpriseinfo.natureOtherDesc
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getNatureotherdesc() {
		return natureotherdesc;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.natureOtherDesc
	 * @param natureotherdesc  the value for enterpriseinfo.natureOtherDesc
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setNatureotherdesc(String natureotherdesc) {
		this.natureotherdesc = natureotherdesc;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.legalRepresentativeTele
	 * @return  the value of enterpriseinfo.legalRepresentativeTele
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getLegalrepresentativetele() {
		return legalrepresentativetele;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.legalRepresentativeTele
	 * @param legalrepresentativetele  the value for enterpriseinfo.legalRepresentativeTele
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setLegalrepresentativetele(String legalrepresentativetele) {
		this.legalrepresentativetele = legalrepresentativetele;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.legalRepresentativeMobile
	 * @return  the value of enterpriseinfo.legalRepresentativeMobile
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getLegalrepresentativemobile() {
		return legalrepresentativemobile;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.legalRepresentativeMobile
	 * @param legalrepresentativemobile  the value for enterpriseinfo.legalRepresentativeMobile
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setLegalrepresentativemobile(String legalrepresentativemobile) {
		this.legalrepresentativemobile = legalrepresentativemobile;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.linkMan
	 * @return  the value of enterpriseinfo.linkMan
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getLinkman() {
		return linkman;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.linkMan
	 * @param linkman  the value for enterpriseinfo.linkMan
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setLinkman(String linkman) {
		this.linkman = linkman;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.spQualifacationLevel
	 * @return  the value of enterpriseinfo.spQualifacationLevel
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getSpqualifacationlevel() {
		return spqualifacationlevel;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.spQualifacationLevel
	 * @param spqualifacationlevel  the value for enterpriseinfo.spQualifacationLevel
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setSpqualifacationlevel(String spqualifacationlevel) {
		this.spqualifacationlevel = spqualifacationlevel;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualityCertifacation
	 * @return  the value of enterpriseinfo.qualityCertifacation
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualitycertifacation() {
		return qualitycertifacation;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualityCertifacation
	 * @param qualitycertifacation  the value for enterpriseinfo.qualityCertifacation
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualitycertifacation(String qualitycertifacation) {
		this.qualitycertifacation = qualitycertifacation;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualityCertifacationOtherDesc
	 * @return  the value of enterpriseinfo.qualityCertifacationOtherDesc
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualitycertifacationotherdesc() {
		return qualitycertifacationotherdesc;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualityCertifacationOtherDesc
	 * @param qualitycertifacationotherdesc  the value for enterpriseinfo.qualityCertifacationOtherDesc
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualitycertifacationotherdesc(
			String qualitycertifacationotherdesc) {
		this.qualitycertifacationotherdesc = qualitycertifacationotherdesc;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.toHighApplyLevel
	 * @return  the value of enterpriseinfo.toHighApplyLevel
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getTohighapplylevel() {
		return tohighapplylevel;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.toHighApplyLevel
	 * @param tohighapplylevel  the value for enterpriseinfo.toHighApplyLevel
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setTohighapplylevel(String tohighapplylevel) {
		this.tohighapplylevel = tohighapplylevel;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMProdProd
	 * @return  the value of enterpriseinfo.OMProdProd
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmprodprod() {
		return omprodprod;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMProdProd
	 * @param omprodprod  the value for enterpriseinfo.OMProdProd
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmprodprod(String omprodprod) {
		this.omprodprod = omprodprod;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMProdSale
	 * @return  the value of enterpriseinfo.OMProdSale
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmprodsale() {
		return omprodsale;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMProdSale
	 * @param omprodsale  the value for enterpriseinfo.OMProdSale
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmprodsale(String omprodsale) {
		this.omprodsale = omprodsale;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMProjMaint
	 * @return  the value of enterpriseinfo.OMProjMaint
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmprojmaint() {
		return omprojmaint;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMProjMaint
	 * @param omprojmaint  the value for enterpriseinfo.OMProjMaint
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmprojmaint(String omprojmaint) {
		this.omprojmaint = omprojmaint;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMNetAlarm
	 * @return  the value of enterpriseinfo.OMNetAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmnetalarm() {
		return omnetalarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMNetAlarm
	 * @param omnetalarm  the value for enterpriseinfo.OMNetAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmnetalarm(String omnetalarm) {
		this.omnetalarm = omnetalarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMspTain
	 * @return  the value of enterpriseinfo.OMspTain
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmsptain() {
		return omsptain;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMspTain
	 * @param omsptain  the value for enterpriseinfo.OMspTain
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmsptain(String omsptain) {
		this.omsptain = omsptain;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMMedia
	 * @return  the value of enterpriseinfo.OMMedia
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmmedia() {
		return ommedia;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMMedia
	 * @param ommedia  the value for enterpriseinfo.OMMedia
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmmedia(String ommedia) {
		this.ommedia = ommedia;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMProjConstruct
	 * @return  the value of enterpriseinfo.OMProjConstruct
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmprojconstruct() {
		return omprojconstruct;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMProjConstruct
	 * @param omprojconstruct  the value for enterpriseinfo.OMProjConstruct
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmprojconstruct(String omprojconstruct) {
		this.omprojconstruct = omprojconstruct;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.OMOther
	 * @return  the value of enterpriseinfo.OMOther
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getOmother() {
		return omother;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.OMOther
	 * @param omother  the value for enterpriseinfo.OMOther
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setOmother(String omother) {
		this.omother = omother;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualifacationGetFire
	 * @return  the value of enterpriseinfo.qualifacationGetFire
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualifacationgetfire() {
		return qualifacationgetfire;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualifacationGetFire
	 * @param qualifacationgetfire  the value for enterpriseinfo.qualifacationGetFire
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualifacationgetfire(String qualifacationgetfire) {
		this.qualifacationgetfire = qualifacationgetfire;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualifacationGetConf
	 * @return  the value of enterpriseinfo.qualifacationGetConf
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualifacationgetconf() {
		return qualifacationgetconf;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualifacationGetConf
	 * @param qualifacationgetconf  the value for enterpriseinfo.qualifacationGetConf
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualifacationgetconf(String qualifacationgetconf) {
		this.qualifacationgetconf = qualifacationgetconf;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualifacationGetBuildInte
	 * @return  the value of enterpriseinfo.qualifacationGetBuildInte
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualifacationgetbuildinte() {
		return qualifacationgetbuildinte;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualifacationGetBuildInte
	 * @param qualifacationgetbuildinte  the value for enterpriseinfo.qualifacationGetBuildInte
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualifacationgetbuildinte(String qualifacationgetbuildinte) {
		this.qualifacationgetbuildinte = qualifacationgetbuildinte;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualifacationGetBuildProj
	 * @return  the value of enterpriseinfo.qualifacationGetBuildProj
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualifacationgetbuildproj() {
		return qualifacationgetbuildproj;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualifacationGetBuildProj
	 * @param qualifacationgetbuildproj  the value for enterpriseinfo.qualifacationGetBuildProj
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualifacationgetbuildproj(String qualifacationgetbuildproj) {
		this.qualifacationgetbuildproj = qualifacationgetbuildproj;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualifacationGetITInte
	 * @return  the value of enterpriseinfo.qualifacationGetITInte
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualifacationgetitinte() {
		return qualifacationgetitinte;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualifacationGetITInte
	 * @param qualifacationgetitinte  the value for enterpriseinfo.qualifacationGetITInte
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualifacationgetitinte(String qualifacationgetitinte) {
		this.qualifacationgetitinte = qualifacationgetitinte;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundVideo
	 * @return  the value of enterpriseinfo.productBoundVideo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundvideo() {
		return productboundvideo;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundVideo
	 * @param productboundvideo  the value for enterpriseinfo.productBoundVideo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundvideo(String productboundvideo) {
		this.productboundvideo = productboundvideo;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundBangSec
	 * @return  the value of enterpriseinfo.productBoundBangSec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundbangsec() {
		return productboundbangsec;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundBangSec
	 * @param productboundbangsec  the value for enterpriseinfo.productBoundBangSec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundbangsec(String productboundbangsec) {
		this.productboundbangsec = productboundbangsec;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundAroundAlarm
	 * @return  the value of enterpriseinfo.productBoundAroundAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundaroundalarm() {
		return productboundaroundalarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundAroundAlarm
	 * @param productboundaroundalarm  the value for enterpriseinfo.productBoundAroundAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundaroundalarm(String productboundaroundalarm) {
		this.productboundaroundalarm = productboundaroundalarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundTheftAlarm
	 * @return  the value of enterpriseinfo.productBoundTheftAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundtheftalarm() {
		return productboundtheftalarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundTheftAlarm
	 * @param productboundtheftalarm  the value for enterpriseinfo.productBoundTheftAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundtheftalarm(String productboundtheftalarm) {
		this.productboundtheftalarm = productboundtheftalarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundEntranceControl
	 * @return  the value of enterpriseinfo.productBoundEntranceControl
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundentrancecontrol() {
		return productboundentrancecontrol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundEntranceControl
	 * @param productboundentrancecontrol  the value for enterpriseinfo.productBoundEntranceControl
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundentrancecontrol(
			String productboundentrancecontrol) {
		this.productboundentrancecontrol = productboundentrancecontrol;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundBuildVoice
	 * @return  the value of enterpriseinfo.productBoundBuildVoice
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundbuildvoice() {
		return productboundbuildvoice;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundBuildVoice
	 * @param productboundbuildvoice  the value for enterpriseinfo.productBoundBuildVoice
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundbuildvoice(String productboundbuildvoice) {
		this.productboundbuildvoice = productboundbuildvoice;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundBuildIntell
	 * @return  the value of enterpriseinfo.productBoundBuildIntell
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundbuildintell() {
		return productboundbuildintell;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundBuildIntell
	 * @param productboundbuildintell  the value for enterpriseinfo.productBoundBuildIntell
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundbuildintell(String productboundbuildintell) {
		this.productboundbuildintell = productboundbuildintell;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundVohileAlarm
	 * @return  the value of enterpriseinfo.productBoundVohileAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundvohilealarm() {
		return productboundvohilealarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundVohileAlarm
	 * @param productboundvohilealarm  the value for enterpriseinfo.productBoundVohileAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundvohilealarm(String productboundvohilealarm) {
		this.productboundvohilealarm = productboundvohilealarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundBodySec
	 * @return  the value of enterpriseinfo.productBoundBodySec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundbodysec() {
		return productboundbodysec;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundBodySec
	 * @param productboundbodysec  the value for enterpriseinfo.productBoundBodySec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundbodysec(String productboundbodysec) {
		this.productboundbodysec = productboundbodysec;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundBaseSec
	 * @return  the value of enterpriseinfo.productBoundBaseSec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductboundbasesec() {
		return productboundbasesec;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundBaseSec
	 * @param productboundbasesec  the value for enterpriseinfo.productBoundBaseSec
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductboundbasesec(String productboundbasesec) {
		this.productboundbasesec = productboundbasesec;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.productBoundDoorAlarm
	 * @return  the value of enterpriseinfo.productBoundDoorAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getProductbounddooralarm() {
		return productbounddooralarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.productBoundDoorAlarm
	 * @param productbounddooralarm  the value for enterpriseinfo.productBoundDoorAlarm
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setProductbounddooralarm(String productbounddooralarm) {
		this.productbounddooralarm = productbounddooralarm;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundFiance
	 * @return  the value of enterpriseinfo.industryBoundFiance
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundfiance() {
		return industryboundfiance;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundFiance
	 * @param industryboundfiance  the value for enterpriseinfo.industryBoundFiance
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundfiance(String industryboundfiance) {
		this.industryboundfiance = industryboundfiance;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundCulture
	 * @return  the value of enterpriseinfo.industryBoundCulture
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundculture() {
		return industryboundculture;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundCulture
	 * @param industryboundculture  the value for enterpriseinfo.industryBoundCulture
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundculture(String industryboundculture) {
		this.industryboundculture = industryboundculture;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundEducation
	 * @return  the value of enterpriseinfo.industryBoundEducation
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundeducation() {
		return industryboundeducation;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundEducation
	 * @param industryboundeducation  the value for enterpriseinfo.industryBoundEducation
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundeducation(String industryboundeducation) {
		this.industryboundeducation = industryboundeducation;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundCommu
	 * @return  the value of enterpriseinfo.industryBoundCommu
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundcommu() {
		return industryboundcommu;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundCommu
	 * @param industryboundcommu  the value for enterpriseinfo.industryBoundCommu
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundcommu(String industryboundcommu) {
		this.industryboundcommu = industryboundcommu;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundGov
	 * @return  the value of enterpriseinfo.industryBoundGov
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundgov() {
		return industryboundgov;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundGov
	 * @param industryboundgov  the value for enterpriseinfo.industryBoundGov
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundgov(String industryboundgov) {
		this.industryboundgov = industryboundgov;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundEnterprise
	 * @return  the value of enterpriseinfo.industryBoundEnterprise
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundenterprise() {
		return industryboundenterprise;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundEnterprise
	 * @param industryboundenterprise  the value for enterpriseinfo.industryBoundEnterprise
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundenterprise(String industryboundenterprise) {
		this.industryboundenterprise = industryboundenterprise;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundEnerge
	 * @return  the value of enterpriseinfo.industryBoundEnerge
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundenerge() {
		return industryboundenerge;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundEnerge
	 * @param industryboundenerge  the value for enterpriseinfo.industryBoundEnerge
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundenerge(String industryboundenerge) {
		this.industryboundenerge = industryboundenerge;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.industryBoundHome
	 * @return  the value of enterpriseinfo.industryBoundHome
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIndustryboundhome() {
		return industryboundhome;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.industryBoundHome
	 * @param industryboundhome  the value for enterpriseinfo.industryBoundHome
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIndustryboundhome(String industryboundhome) {
		this.industryboundhome = industryboundhome;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.totalAssets
	 * @return  the value of enterpriseinfo.totalAssets
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Double getTotalassets() {
		return totalassets;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.totalAssets
	 * @param totalassets  the value for enterpriseinfo.totalAssets
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setTotalassets(Double totalassets) {
		this.totalassets = totalassets;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.businessIncome
	 * @return  the value of enterpriseinfo.businessIncome
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Double getBusinessincome() {
		return businessincome;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.businessIncome
	 * @param businessincome  the value for enterpriseinfo.businessIncome
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setBusinessincome(Double businessincome) {
		this.businessincome = businessincome;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.netProfit
	 * @return  the value of enterpriseinfo.netProfit
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public Double getNetprofit() {
		return netprofit;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.netProfit
	 * @param netprofit  the value for enterpriseinfo.netProfit
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setNetprofit(Double netprofit) {
		this.netprofit = netprofit;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualificationSupervision
	 * @return  the value of enterpriseinfo.qualificationSupervision
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualificationsupervision() {
		return qualificationsupervision;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualificationSupervision
	 * @param qualificationsupervision  the value for enterpriseinfo.qualificationSupervision
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualificationsupervision(String qualificationsupervision) {
		this.qualificationsupervision = qualificationsupervision;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.qualificationComputerSp
	 * @return  the value of enterpriseinfo.qualificationComputerSp
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getQualificationcomputersp() {
		return qualificationcomputersp;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.qualificationComputerSp
	 * @param qualificationcomputersp  the value for enterpriseinfo.qualificationComputerSp
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setQualificationcomputersp(String qualificationcomputersp) {
		this.qualificationcomputersp = qualificationcomputersp;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns the value of the database column enterpriseinfo.introduction
	 * @return  the value of enterpriseinfo.introduction
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public String getIntroduction() {
		return introduction;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the value of the database column enterpriseinfo.introduction
	 * @param introduction  the value for enterpriseinfo.introduction
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void setIntroduction(String introduction) {
		this.introduction = introduction;
	}

	private String natureDescription;
    private String operationDescripton;
	private String memberTypeDescription;    
	private String createdUserName;
	private String lastUpdateUserName;
	private String IPODescription;
	private String feePaymentDescription;
	private String spQualifacationLevelDescripton;
	private String qualityCertifacationDescripton;
	private String toHighApplyLevelDescripton;
	private String litigationGetYear;
	private String qualifacationGetFireDesc;
	private String qualifacationGetConfDesc;
	private String qualifacationGetBuildInteDesc;
	private String qualifacationGetBuildProjDesc;
	private String qualifacationGetITInteDesc;
	private String qualificationSupervisionDesc;
	private String qualificationComputerSpDesc;
	
	
	public String getQualificationSupervisionDesc() {
		return qualificationSupervisionDesc;
	}

	public void setQualificationSupervisionDesc(String qualificationSupervisionDesc) {
		this.qualificationSupervisionDesc = qualificationSupervisionDesc;
	}

	public String getQualificationComputerSpDesc() {
		return qualificationComputerSpDesc;
	}

	public void setQualificationComputerSpDesc(String qualificationComputerSpDesc) {
		this.qualificationComputerSpDesc = qualificationComputerSpDesc;
	}

	public String getLitigationGetYear() {
		return litigationGetYear;
	}

	public void setLitigationGetYear(String litigationGetYear) {
		this.litigationGetYear = litigationGetYear;
	}

	public String getQualifacationGetFireDesc() {
		return qualifacationGetFireDesc;
	}

	public void setQualifacationGetFireDesc(String qualifacationGetFireDesc) {
		this.qualifacationGetFireDesc = qualifacationGetFireDesc;
	}

	public String getQualifacationGetConfDesc() {
		return qualifacationGetConfDesc;
	}

	public void setQualifacationGetConfDesc(String qualifacationGetConfDesc) {
		this.qualifacationGetConfDesc = qualifacationGetConfDesc;
	}

	public String getQualifacationGetBuildInteDesc() {
		return qualifacationGetBuildInteDesc;
	}

	public void setQualifacationGetBuildInteDesc(
			String qualifacationGetBuildInteDesc) {
		this.qualifacationGetBuildInteDesc = qualifacationGetBuildInteDesc;
	}

	public String getQualifacationGetBuildProjDesc() {
		return qualifacationGetBuildProjDesc;
	}

	public void setQualifacationGetBuildProjDesc(
			String qualifacationGetBuildProjDesc) {
		this.qualifacationGetBuildProjDesc = qualifacationGetBuildProjDesc;
	}

	public String getQualifacationGetITInteDesc() {
		return qualifacationGetITInteDesc;
	}

	public void setQualifacationGetITInteDesc(String qualifacationGetITInteDesc) {
		this.qualifacationGetITInteDesc = qualifacationGetITInteDesc;
	}

	public String getToHighApplyLevelDescripton() {
		return toHighApplyLevelDescripton;
	}

	public void setToHighApplyLevelDescripton(String toHighApplyLevelDescripton) {
		this.toHighApplyLevelDescripton = toHighApplyLevelDescripton;
	}

	public String getSpQualifacationLevelDescripton() {
		return spQualifacationLevelDescripton;
	}

	public void setSpQualifacationLevelDescripton(
			String spQualifacationLevelDescripton) {
		this.spQualifacationLevelDescripton = spQualifacationLevelDescripton;
	}

	public String getQualityCertifacationDescripton() {
		return qualityCertifacationDescripton;
	}

	public void setQualityCertifacationDescripton(
			String qualityCertifacationDescripton) {
		this.qualityCertifacationDescripton = qualityCertifacationDescripton;
	}
	
	public String getIPODescription() {
		return IPODescription;
	}

	public void setIPODescription(String iPODescription) {
		IPODescription = iPODescription;
	}

	public String getFeePaymentDescription() {
		return feePaymentDescription;
	}

	public void setFeePaymentDescription(String feePaymentDescription) {
		this.feePaymentDescription = feePaymentDescription;
	}

	public String getNatureDescription() {
		return natureDescription;
	}

	public void setNatureDescription(String natureDescription) {
		this.natureDescription = natureDescription;
	}
    

	public String getOperationDescripton() {
		return operationDescripton;
	}

	public void setOperationDescripton(String operationDescripton) {
		this.operationDescripton = operationDescripton;
	}


	public String getMemberTypeDescription() {
		return memberTypeDescription;
	}

	public void setMemberTypeDescription(String memberTypeDescription) {
		this.memberTypeDescription = memberTypeDescription;
	}
	

	public String getCreatedUserName() {
		return createdUserName;
	}

	public void setCreatedUserName(String createdUserName) {
		this.createdUserName = createdUserName;
	}

	public String getLastUpdateUserName() {
		return lastUpdateUserName;
	}

	public void setLastUpdateUserName(String lastUpdateUserName) {
		this.lastUpdateUserName = lastUpdateUserName;
	}

	@Override
	public String getForeignKey() {
		return createdloginid;
	}

	@Override
	public String getPrimaryKey() {
		return id;
	}

	@Override
	public void setForeignKey(String arg0) {
		createdloginid = arg0;
	}

	@Override
	public void setPrimaryKey(String arg0) {
		id = arg0;
	}
}