package com.meidusa.demo.dal.model;

import com.meidusa.demo.dal.model.EnumerationExample;
import com.meidusa.toolkit.dal.ibator.AbstractExample;
import java.util.List;

public class EnumerationExample extends AbstractExample<EnumerationExample.Criteria> {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enumeration
     *
     * @ibatorgenerated Sun Mar 21 12:03:13 CST 2010
     */
    public EnumerationExample() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enumeration
     *
     * @ibatorgenerated Sun Mar 21 12:03:13 CST 2010
     */
    public EnumerationExample(EnumerationExample example) {
        super(example);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enumeration
     *
     * @ibatorgenerated Sun Mar 21 12:03:13 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table enumeration
     *
     * @ibatorgenerated Sun Mar 21 12:03:13 CST 2010
     */
    public static class Criteria extends AbstractExample.Criteria {

        public Criteria andForeignKeyEqualTo(String value) {
            addCriterion("null like", value, "null");
            return this;
        }

        public Criteria andEnumidIsNull() {
            addCriterion("enumId is null");
            return this;
        }

        public Criteria andEnumidIsNotNull() {
            addCriterion("enumId is not null");
            return this;
        }

        public Criteria andEnumidEqualTo(String value) {
            addCriterion("enumId =", value, "enumid");
            return this;
        }

        public Criteria andEnumidNotEqualTo(String value) {
            addCriterion("enumId <>", value, "enumid");
            return this;
        }

        public Criteria andEnumidGreaterThan(String value) {
            addCriterion("enumId >", value, "enumid");
            return this;
        }

        public Criteria andEnumidGreaterThanOrEqualTo(String value) {
            addCriterion("enumId >=", value, "enumid");
            return this;
        }

        public Criteria andEnumidLessThan(String value) {
            addCriterion("enumId <", value, "enumid");
            return this;
        }

        public Criteria andEnumidLessThanOrEqualTo(String value) {
            addCriterion("enumId <=", value, "enumid");
            return this;
        }

        public Criteria andEnumidLike(String value) {
            addCriterion("enumId like", value, "enumid");
            return this;
        }

        public Criteria andEnumidNotLike(String value) {
            addCriterion("enumId not like", value, "enumid");
            return this;
        }

        public Criteria andEnumidIn(List<String> values) {
            addCriterion("enumId in", values, "enumid");
            return this;
        }

        public Criteria andEnumidNotIn(List<String> values) {
            addCriterion("enumId not in", values, "enumid");
            return this;
        }

        public Criteria andEnumidBetween(String value1, String value2) {
            addCriterion("enumId between", value1, value2, "enumid");
            return this;
        }

        public Criteria andEnumidNotBetween(String value1, String value2) {
            addCriterion("enumId not between", value1, value2, "enumid");
            return this;
        }

        public Criteria andEnumcodeIsNull() {
            addCriterion("enumCode is null");
            return this;
        }

        public Criteria andEnumcodeIsNotNull() {
            addCriterion("enumCode is not null");
            return this;
        }

        public Criteria andEnumcodeEqualTo(String value) {
            addCriterion("enumCode =", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeNotEqualTo(String value) {
            addCriterion("enumCode <>", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeGreaterThan(String value) {
            addCriterion("enumCode >", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeGreaterThanOrEqualTo(String value) {
            addCriterion("enumCode >=", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeLessThan(String value) {
            addCriterion("enumCode <", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeLessThanOrEqualTo(String value) {
            addCriterion("enumCode <=", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeLike(String value) {
            addCriterion("enumCode like", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeNotLike(String value) {
            addCriterion("enumCode not like", value, "enumcode");
            return this;
        }

        public Criteria andEnumcodeIn(List<String> values) {
            addCriterion("enumCode in", values, "enumcode");
            return this;
        }

        public Criteria andEnumcodeNotIn(List<String> values) {
            addCriterion("enumCode not in", values, "enumcode");
            return this;
        }

        public Criteria andEnumcodeBetween(String value1, String value2) {
            addCriterion("enumCode between", value1, value2, "enumcode");
            return this;
        }

        public Criteria andEnumcodeNotBetween(String value1, String value2) {
            addCriterion("enumCode not between", value1, value2, "enumcode");
            return this;
        }

        public Criteria andEnumtypeidIsNull() {
            addCriterion("enumTypeId is null");
            return this;
        }

        public Criteria andEnumtypeidIsNotNull() {
            addCriterion("enumTypeId is not null");
            return this;
        }

        public Criteria andEnumtypeidEqualTo(String value) {
            addCriterion("enumTypeId =", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidNotEqualTo(String value) {
            addCriterion("enumTypeId <>", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidGreaterThan(String value) {
            addCriterion("enumTypeId >", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidGreaterThanOrEqualTo(String value) {
            addCriterion("enumTypeId >=", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidLessThan(String value) {
            addCriterion("enumTypeId <", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidLessThanOrEqualTo(String value) {
            addCriterion("enumTypeId <=", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidLike(String value) {
            addCriterion("enumTypeId like", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidNotLike(String value) {
            addCriterion("enumTypeId not like", value, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidIn(List<String> values) {
            addCriterion("enumTypeId in", values, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidNotIn(List<String> values) {
            addCriterion("enumTypeId not in", values, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidBetween(String value1, String value2) {
            addCriterion("enumTypeId between", value1, value2, "enumtypeid");
            return this;
        }

        public Criteria andEnumtypeidNotBetween(String value1, String value2) {
            addCriterion("enumTypeId not between", value1, value2, "enumtypeid");
            return this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("description is null");
            return this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("description is not null");
            return this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("description =", value, "description");
            return this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("description <>", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("description >", value, "description");
            return this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("description >=", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("description <", value, "description");
            return this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("description <=", value, "description");
            return this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("description like", value, "description");
            return this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("description not like", value, "description");
            return this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("description in", values, "description");
            return this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("description not in", values, "description");
            return this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("description between", value1, value2, "description");
            return this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("description not between", value1, value2, "description");
            return this;
        }
    }
}