package com.meidusa.demo.dal.model;

import com.meidusa.toolkit.dal.ibator.AbstractModel;
import java.util.Date;

public class Examination extends AbstractModel {
	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.id
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String id;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.examName
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String examname;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.examAddr
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String examaddr;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.examTypeEnumId
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String examtypeenumid;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.examDuring
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String examduring;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.examCount
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private Integer examcount;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.contact
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String contact;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.tel
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String tel;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.email
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private String email;

	/**
	 * This field was generated by Apache iBATIS Ibator. This field corresponds
	 * to the database column examination.lastupdatetimestamp
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	private Date lastupdatetimestamp;

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.id
	 * 
	 * @return the value of examination.id
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getId() {
		return id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.id
	 * 
	 * @param id
	 *            the value for examination.id
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setId(String id) {
		this.id = id;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.examName
	 * 
	 * @return the value of examination.examName
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getExamname() {
		return examname;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.examName
	 * 
	 * @param examname
	 *            the value for examination.examName
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setExamname(String examname) {
		this.examname = examname;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.examAddr
	 * 
	 * @return the value of examination.examAddr
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getExamaddr() {
		return examaddr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.examAddr
	 * 
	 * @param examaddr
	 *            the value for examination.examAddr
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setExamaddr(String examaddr) {
		this.examaddr = examaddr;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.examTypeEnumId
	 * 
	 * @return the value of examination.examTypeEnumId
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getExamtypeenumid() {
		return examtypeenumid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.examTypeEnumId
	 * 
	 * @param examtypeenumid
	 *            the value for examination.examTypeEnumId
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setExamtypeenumid(String examtypeenumid) {
		this.examtypeenumid = examtypeenumid;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.examDuring
	 * 
	 * @return the value of examination.examDuring
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getExamduring() {
		return examduring;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.examDuring
	 * 
	 * @param examduring
	 *            the value for examination.examDuring
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setExamduring(String examduring) {
		this.examduring = examduring;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.examCount
	 * 
	 * @return the value of examination.examCount
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public Integer getExamcount() {
		return examcount;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.examCount
	 * 
	 * @param examcount
	 *            the value for examination.examCount
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setExamcount(Integer examcount) {
		this.examcount = examcount;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.contact
	 * 
	 * @return the value of examination.contact
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.contact
	 * 
	 * @param contact
	 *            the value for examination.contact
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.tel
	 * 
	 * @return the value of examination.tel
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.tel
	 * 
	 * @param tel
	 *            the value for examination.tel
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.email
	 * 
	 * @return the value of examination.email
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.email
	 * 
	 * @param email
	 *            the value for examination.email
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method returns
	 * the value of the database column examination.lastupdatetimestamp
	 * 
	 * @return the value of examination.lastupdatetimestamp
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public Date getLastupdatetimestamp() {
		return lastupdatetimestamp;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method sets the
	 * value of the database column examination.lastupdatetimestamp
	 * 
	 * @param lastupdatetimestamp
	 *            the value for examination.lastupdatetimestamp
	 * 
	 * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
	 */
	public void setLastupdatetimestamp(Date lastupdatetimestamp) {
		this.lastupdatetimestamp = lastupdatetimestamp;
	}

	private String examtypedesc;
	
	
	public String getExamtypedesc() {
		return examtypedesc;
	}

	public void setExamtypedesc(String examtypedesc) {
		this.examtypedesc = examtypedesc;
	}

	@Override
	public String getForeignKey() {
		return examname;
	}

	@Override
	public String getPrimaryKey() {
		return id;
	}

	@Override
	public void setForeignKey(String arg0) {
		examname = arg0;

	}

	@Override
	public void setPrimaryKey(String arg0) {
		id = arg0;

	}
}