package com.meidusa.demo.dal.model;

import com.meidusa.demo.dal.model.ExaminationExample;
import com.meidusa.toolkit.dal.ibator.AbstractExample;
import java.util.Date;
import java.util.List;

public class ExaminationExample extends AbstractExample<ExaminationExample.Criteria> {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    public ExaminationExample() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    public ExaminationExample(ExaminationExample example) {
        super(example);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    public static class Criteria extends AbstractExample.Criteria {

        public Criteria andForeignKeyEqualTo(String value) {
            addCriterion("null like", value, "null");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andExamnameIsNull() {
            addCriterion("examName is null");
            return this;
        }

        public Criteria andExamnameIsNotNull() {
            addCriterion("examName is not null");
            return this;
        }

        public Criteria andExamnameEqualTo(String value) {
            addCriterion("examName =", value, "examname");
            return this;
        }

        public Criteria andExamnameNotEqualTo(String value) {
            addCriterion("examName <>", value, "examname");
            return this;
        }

        public Criteria andExamnameGreaterThan(String value) {
            addCriterion("examName >", value, "examname");
            return this;
        }

        public Criteria andExamnameGreaterThanOrEqualTo(String value) {
            addCriterion("examName >=", value, "examname");
            return this;
        }

        public Criteria andExamnameLessThan(String value) {
            addCriterion("examName <", value, "examname");
            return this;
        }

        public Criteria andExamnameLessThanOrEqualTo(String value) {
            addCriterion("examName <=", value, "examname");
            return this;
        }

        public Criteria andExamnameLike(String value) {
            addCriterion("examName like", value, "examname");
            return this;
        }

        public Criteria andExamnameNotLike(String value) {
            addCriterion("examName not like", value, "examname");
            return this;
        }

        public Criteria andExamnameIn(List<String> values) {
            addCriterion("examName in", values, "examname");
            return this;
        }

        public Criteria andExamnameNotIn(List<String> values) {
            addCriterion("examName not in", values, "examname");
            return this;
        }

        public Criteria andExamnameBetween(String value1, String value2) {
            addCriterion("examName between", value1, value2, "examname");
            return this;
        }

        public Criteria andExamnameNotBetween(String value1, String value2) {
            addCriterion("examName not between", value1, value2, "examname");
            return this;
        }

        public Criteria andExamaddrIsNull() {
            addCriterion("examAddr is null");
            return this;
        }

        public Criteria andExamaddrIsNotNull() {
            addCriterion("examAddr is not null");
            return this;
        }

        public Criteria andExamaddrEqualTo(String value) {
            addCriterion("examAddr =", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrNotEqualTo(String value) {
            addCriterion("examAddr <>", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrGreaterThan(String value) {
            addCriterion("examAddr >", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrGreaterThanOrEqualTo(String value) {
            addCriterion("examAddr >=", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrLessThan(String value) {
            addCriterion("examAddr <", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrLessThanOrEqualTo(String value) {
            addCriterion("examAddr <=", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrLike(String value) {
            addCriterion("examAddr like", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrNotLike(String value) {
            addCriterion("examAddr not like", value, "examaddr");
            return this;
        }

        public Criteria andExamaddrIn(List<String> values) {
            addCriterion("examAddr in", values, "examaddr");
            return this;
        }

        public Criteria andExamaddrNotIn(List<String> values) {
            addCriterion("examAddr not in", values, "examaddr");
            return this;
        }

        public Criteria andExamaddrBetween(String value1, String value2) {
            addCriterion("examAddr between", value1, value2, "examaddr");
            return this;
        }

        public Criteria andExamaddrNotBetween(String value1, String value2) {
            addCriterion("examAddr not between", value1, value2, "examaddr");
            return this;
        }

        public Criteria andExamtypeenumidIsNull() {
            addCriterion("examTypeEnumId is null");
            return this;
        }

        public Criteria andExamtypeenumidIsNotNull() {
            addCriterion("examTypeEnumId is not null");
            return this;
        }

        public Criteria andExamtypeenumidEqualTo(String value) {
            addCriterion("examTypeEnumId =", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidNotEqualTo(String value) {
            addCriterion("examTypeEnumId <>", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidGreaterThan(String value) {
            addCriterion("examTypeEnumId >", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidGreaterThanOrEqualTo(String value) {
            addCriterion("examTypeEnumId >=", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidLessThan(String value) {
            addCriterion("examTypeEnumId <", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidLessThanOrEqualTo(String value) {
            addCriterion("examTypeEnumId <=", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidLike(String value) {
            addCriterion("examTypeEnumId like", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidNotLike(String value) {
            addCriterion("examTypeEnumId not like", value, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidIn(List<String> values) {
            addCriterion("examTypeEnumId in", values, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidNotIn(List<String> values) {
            addCriterion("examTypeEnumId not in", values, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidBetween(String value1, String value2) {
            addCriterion("examTypeEnumId between", value1, value2, "examtypeenumid");
            return this;
        }

        public Criteria andExamtypeenumidNotBetween(String value1, String value2) {
            addCriterion("examTypeEnumId not between", value1, value2, "examtypeenumid");
            return this;
        }

        public Criteria andExamduringIsNull() {
            addCriterion("examDuring is null");
            return this;
        }

        public Criteria andExamduringIsNotNull() {
            addCriterion("examDuring is not null");
            return this;
        }

        public Criteria andExamduringEqualTo(String value) {
            addCriterion("examDuring =", value, "examduring");
            return this;
        }

        public Criteria andExamduringNotEqualTo(String value) {
            addCriterion("examDuring <>", value, "examduring");
            return this;
        }

        public Criteria andExamduringGreaterThan(String value) {
            addCriterion("examDuring >", value, "examduring");
            return this;
        }

        public Criteria andExamduringGreaterThanOrEqualTo(String value) {
            addCriterion("examDuring >=", value, "examduring");
            return this;
        }

        public Criteria andExamduringLessThan(String value) {
            addCriterion("examDuring <", value, "examduring");
            return this;
        }

        public Criteria andExamduringLessThanOrEqualTo(String value) {
            addCriterion("examDuring <=", value, "examduring");
            return this;
        }

        public Criteria andExamduringLike(String value) {
            addCriterion("examDuring like", value, "examduring");
            return this;
        }

        public Criteria andExamduringNotLike(String value) {
            addCriterion("examDuring not like", value, "examduring");
            return this;
        }

        public Criteria andExamduringIn(List<String> values) {
            addCriterion("examDuring in", values, "examduring");
            return this;
        }

        public Criteria andExamduringNotIn(List<String> values) {
            addCriterion("examDuring not in", values, "examduring");
            return this;
        }

        public Criteria andExamduringBetween(String value1, String value2) {
            addCriterion("examDuring between", value1, value2, "examduring");
            return this;
        }

        public Criteria andExamduringNotBetween(String value1, String value2) {
            addCriterion("examDuring not between", value1, value2, "examduring");
            return this;
        }

        public Criteria andExamcountIsNull() {
            addCriterion("examCount is null");
            return this;
        }

        public Criteria andExamcountIsNotNull() {
            addCriterion("examCount is not null");
            return this;
        }

        public Criteria andExamcountEqualTo(Integer value) {
            addCriterion("examCount =", value, "examcount");
            return this;
        }

        public Criteria andExamcountNotEqualTo(Integer value) {
            addCriterion("examCount <>", value, "examcount");
            return this;
        }

        public Criteria andExamcountGreaterThan(Integer value) {
            addCriterion("examCount >", value, "examcount");
            return this;
        }

        public Criteria andExamcountGreaterThanOrEqualTo(Integer value) {
            addCriterion("examCount >=", value, "examcount");
            return this;
        }

        public Criteria andExamcountLessThan(Integer value) {
            addCriterion("examCount <", value, "examcount");
            return this;
        }

        public Criteria andExamcountLessThanOrEqualTo(Integer value) {
            addCriterion("examCount <=", value, "examcount");
            return this;
        }

        public Criteria andExamcountIn(List<Integer> values) {
            addCriterion("examCount in", values, "examcount");
            return this;
        }

        public Criteria andExamcountNotIn(List<Integer> values) {
            addCriterion("examCount not in", values, "examcount");
            return this;
        }

        public Criteria andExamcountBetween(Integer value1, Integer value2) {
            addCriterion("examCount between", value1, value2, "examcount");
            return this;
        }

        public Criteria andExamcountNotBetween(Integer value1, Integer value2) {
            addCriterion("examCount not between", value1, value2, "examcount");
            return this;
        }

        public Criteria andContactIsNull() {
            addCriterion("contact is null");
            return this;
        }

        public Criteria andContactIsNotNull() {
            addCriterion("contact is not null");
            return this;
        }

        public Criteria andContactEqualTo(String value) {
            addCriterion("contact =", value, "contact");
            return this;
        }

        public Criteria andContactNotEqualTo(String value) {
            addCriterion("contact <>", value, "contact");
            return this;
        }

        public Criteria andContactGreaterThan(String value) {
            addCriterion("contact >", value, "contact");
            return this;
        }

        public Criteria andContactGreaterThanOrEqualTo(String value) {
            addCriterion("contact >=", value, "contact");
            return this;
        }

        public Criteria andContactLessThan(String value) {
            addCriterion("contact <", value, "contact");
            return this;
        }

        public Criteria andContactLessThanOrEqualTo(String value) {
            addCriterion("contact <=", value, "contact");
            return this;
        }

        public Criteria andContactLike(String value) {
            addCriterion("contact like", value, "contact");
            return this;
        }

        public Criteria andContactNotLike(String value) {
            addCriterion("contact not like", value, "contact");
            return this;
        }

        public Criteria andContactIn(List<String> values) {
            addCriterion("contact in", values, "contact");
            return this;
        }

        public Criteria andContactNotIn(List<String> values) {
            addCriterion("contact not in", values, "contact");
            return this;
        }

        public Criteria andContactBetween(String value1, String value2) {
            addCriterion("contact between", value1, value2, "contact");
            return this;
        }

        public Criteria andContactNotBetween(String value1, String value2) {
            addCriterion("contact not between", value1, value2, "contact");
            return this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return this;
        }

        public Criteria andLastupdatetimestampIsNull() {
            addCriterion("lastupdatetimestamp is null");
            return this;
        }

        public Criteria andLastupdatetimestampIsNotNull() {
            addCriterion("lastupdatetimestamp is not null");
            return this;
        }

        public Criteria andLastupdatetimestampEqualTo(Date value) {
            addCriterion("lastupdatetimestamp =", value, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampNotEqualTo(Date value) {
            addCriterion("lastupdatetimestamp <>", value, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampGreaterThan(Date value) {
            addCriterion("lastupdatetimestamp >", value, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampGreaterThanOrEqualTo(Date value) {
            addCriterion("lastupdatetimestamp >=", value, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampLessThan(Date value) {
            addCriterion("lastupdatetimestamp <", value, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampLessThanOrEqualTo(Date value) {
            addCriterion("lastupdatetimestamp <=", value, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampIn(List<Date> values) {
            addCriterion("lastupdatetimestamp in", values, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampNotIn(List<Date> values) {
            addCriterion("lastupdatetimestamp not in", values, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampBetween(Date value1, Date value2) {
            addCriterion("lastupdatetimestamp between", value1, value2, "lastupdatetimestamp");
            return this;
        }

        public Criteria andLastupdatetimestampNotBetween(Date value1, Date value2) {
            addCriterion("lastupdatetimestamp not between", value1, value2, "lastupdatetimestamp");
            return this;
        }
    }
}