package com.meidusa.demo.dal.model;

public class ExcellentSelectionWithBLOBs extends ExcellentSelection {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.introduction
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String introduction;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.requestPublish
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String requestpublish;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.workIntroduction
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String workintroduction;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.enterpriseRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String enterpriseremark;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.otherRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String otherremark;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.checkReport
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String checkreport;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.introduction
     *
     * @return the value of excellentselection.introduction
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.introduction
     *
     * @param introduction the value for excellentselection.introduction
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.requestPublish
     *
     * @return the value of excellentselection.requestPublish
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getRequestpublish() {
        return requestpublish;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.requestPublish
     *
     * @param requestpublish the value for excellentselection.requestPublish
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setRequestpublish(String requestpublish) {
        this.requestpublish = requestpublish;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.workIntroduction
     *
     * @return the value of excellentselection.workIntroduction
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getWorkintroduction() {
        return workintroduction;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.workIntroduction
     *
     * @param workintroduction the value for excellentselection.workIntroduction
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setWorkintroduction(String workintroduction) {
        this.workintroduction = workintroduction;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.enterpriseRemark
     *
     * @return the value of excellentselection.enterpriseRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getEnterpriseremark() {
        return enterpriseremark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.enterpriseRemark
     *
     * @param enterpriseremark the value for excellentselection.enterpriseRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setEnterpriseremark(String enterpriseremark) {
        this.enterpriseremark = enterpriseremark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.otherRemark
     *
     * @return the value of excellentselection.otherRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getOtherremark() {
        return otherremark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.otherRemark
     *
     * @param otherremark the value for excellentselection.otherRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setOtherremark(String otherremark) {
        this.otherremark = otherremark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.checkReport
     *
     * @return the value of excellentselection.checkReport
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getCheckreport() {
        return checkreport;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.checkReport
     *
     * @param checkreport the value for excellentselection.checkReport
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setCheckreport(String checkreport) {
        this.checkreport = checkreport;
    }
}