package com.meidusa.demo.dal.model;

import com.meidusa.demo.dal.model.ExcellentSelectionExample;
import com.meidusa.toolkit.dal.ibator.AbstractExample;
import java.util.List;

public class ExcellentSelectionExample extends AbstractExample<ExcellentSelectionExample.Criteria> {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table excellentselection
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public ExcellentSelectionExample() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table excellentselection
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public ExcellentSelectionExample(ExcellentSelectionExample example) {
        super(example);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table excellentselection
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table excellentselection
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public static class Criteria extends AbstractExample.Criteria {

        public Criteria andForeignKeyEqualTo(String value) {
            addCriterion("null like", value, "null");
            return this;
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return this;
        }

        public Criteria andEnterprisenameIsNull() {
            addCriterion("enterpriseName is null");
            return this;
        }

        public Criteria andEnterprisenameIsNotNull() {
            addCriterion("enterpriseName is not null");
            return this;
        }

        public Criteria andEnterprisenameEqualTo(String value) {
            addCriterion("enterpriseName =", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameNotEqualTo(String value) {
            addCriterion("enterpriseName <>", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameGreaterThan(String value) {
            addCriterion("enterpriseName >", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameGreaterThanOrEqualTo(String value) {
            addCriterion("enterpriseName >=", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameLessThan(String value) {
            addCriterion("enterpriseName <", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameLessThanOrEqualTo(String value) {
            addCriterion("enterpriseName <=", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameLike(String value) {
            addCriterion("enterpriseName like", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameNotLike(String value) {
            addCriterion("enterpriseName not like", value, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameIn(List<String> values) {
            addCriterion("enterpriseName in", values, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameNotIn(List<String> values) {
            addCriterion("enterpriseName not in", values, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameBetween(String value1, String value2) {
            addCriterion("enterpriseName between", value1, value2, "enterprisename");
            return this;
        }

        public Criteria andEnterprisenameNotBetween(String value1, String value2) {
            addCriterion("enterpriseName not between", value1, value2, "enterprisename");
            return this;
        }

        public Criteria andLegalrepresentativeIsNull() {
            addCriterion("legalRepresentative is null");
            return this;
        }

        public Criteria andLegalrepresentativeIsNotNull() {
            addCriterion("legalRepresentative is not null");
            return this;
        }

        public Criteria andLegalrepresentativeEqualTo(String value) {
            addCriterion("legalRepresentative =", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeNotEqualTo(String value) {
            addCriterion("legalRepresentative <>", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeGreaterThan(String value) {
            addCriterion("legalRepresentative >", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeGreaterThanOrEqualTo(String value) {
            addCriterion("legalRepresentative >=", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeLessThan(String value) {
            addCriterion("legalRepresentative <", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeLessThanOrEqualTo(String value) {
            addCriterion("legalRepresentative <=", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeLike(String value) {
            addCriterion("legalRepresentative like", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeNotLike(String value) {
            addCriterion("legalRepresentative not like", value, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeIn(List<String> values) {
            addCriterion("legalRepresentative in", values, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeNotIn(List<String> values) {
            addCriterion("legalRepresentative not in", values, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeBetween(String value1, String value2) {
            addCriterion("legalRepresentative between", value1, value2, "legalrepresentative");
            return this;
        }

        public Criteria andLegalrepresentativeNotBetween(String value1, String value2) {
            addCriterion("legalRepresentative not between", value1, value2, "legalrepresentative");
            return this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return this;
        }

        public Criteria andRequestnameIsNull() {
            addCriterion("requestName is null");
            return this;
        }

        public Criteria andRequestnameIsNotNull() {
            addCriterion("requestName is not null");
            return this;
        }

        public Criteria andRequestnameEqualTo(String value) {
            addCriterion("requestName =", value, "requestname");
            return this;
        }

        public Criteria andRequestnameNotEqualTo(String value) {
            addCriterion("requestName <>", value, "requestname");
            return this;
        }

        public Criteria andRequestnameGreaterThan(String value) {
            addCriterion("requestName >", value, "requestname");
            return this;
        }

        public Criteria andRequestnameGreaterThanOrEqualTo(String value) {
            addCriterion("requestName >=", value, "requestname");
            return this;
        }

        public Criteria andRequestnameLessThan(String value) {
            addCriterion("requestName <", value, "requestname");
            return this;
        }

        public Criteria andRequestnameLessThanOrEqualTo(String value) {
            addCriterion("requestName <=", value, "requestname");
            return this;
        }

        public Criteria andRequestnameLike(String value) {
            addCriterion("requestName like", value, "requestname");
            return this;
        }

        public Criteria andRequestnameNotLike(String value) {
            addCriterion("requestName not like", value, "requestname");
            return this;
        }

        public Criteria andRequestnameIn(List<String> values) {
            addCriterion("requestName in", values, "requestname");
            return this;
        }

        public Criteria andRequestnameNotIn(List<String> values) {
            addCriterion("requestName not in", values, "requestname");
            return this;
        }

        public Criteria andRequestnameBetween(String value1, String value2) {
            addCriterion("requestName between", value1, value2, "requestname");
            return this;
        }

        public Criteria andRequestnameNotBetween(String value1, String value2) {
            addCriterion("requestName not between", value1, value2, "requestname");
            return this;
        }

        public Criteria andRequestoldIsNull() {
            addCriterion("requestOld is null");
            return this;
        }

        public Criteria andRequestoldIsNotNull() {
            addCriterion("requestOld is not null");
            return this;
        }

        public Criteria andRequestoldEqualTo(String value) {
            addCriterion("requestOld =", value, "requestold");
            return this;
        }

        public Criteria andRequestoldNotEqualTo(String value) {
            addCriterion("requestOld <>", value, "requestold");
            return this;
        }

        public Criteria andRequestoldGreaterThan(String value) {
            addCriterion("requestOld >", value, "requestold");
            return this;
        }

        public Criteria andRequestoldGreaterThanOrEqualTo(String value) {
            addCriterion("requestOld >=", value, "requestold");
            return this;
        }

        public Criteria andRequestoldLessThan(String value) {
            addCriterion("requestOld <", value, "requestold");
            return this;
        }

        public Criteria andRequestoldLessThanOrEqualTo(String value) {
            addCriterion("requestOld <=", value, "requestold");
            return this;
        }

        public Criteria andRequestoldLike(String value) {
            addCriterion("requestOld like", value, "requestold");
            return this;
        }

        public Criteria andRequestoldNotLike(String value) {
            addCriterion("requestOld not like", value, "requestold");
            return this;
        }

        public Criteria andRequestoldIn(List<String> values) {
            addCriterion("requestOld in", values, "requestold");
            return this;
        }

        public Criteria andRequestoldNotIn(List<String> values) {
            addCriterion("requestOld not in", values, "requestold");
            return this;
        }

        public Criteria andRequestoldBetween(String value1, String value2) {
            addCriterion("requestOld between", value1, value2, "requestold");
            return this;
        }

        public Criteria andRequestoldNotBetween(String value1, String value2) {
            addCriterion("requestOld not between", value1, value2, "requestold");
            return this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return this;
        }

        public Criteria andSpworkduringIsNull() {
            addCriterion("spWorkDuring is null");
            return this;
        }

        public Criteria andSpworkduringIsNotNull() {
            addCriterion("spWorkDuring is not null");
            return this;
        }

        public Criteria andSpworkduringEqualTo(String value) {
            addCriterion("spWorkDuring =", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringNotEqualTo(String value) {
            addCriterion("spWorkDuring <>", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringGreaterThan(String value) {
            addCriterion("spWorkDuring >", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringGreaterThanOrEqualTo(String value) {
            addCriterion("spWorkDuring >=", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringLessThan(String value) {
            addCriterion("spWorkDuring <", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringLessThanOrEqualTo(String value) {
            addCriterion("spWorkDuring <=", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringLike(String value) {
            addCriterion("spWorkDuring like", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringNotLike(String value) {
            addCriterion("spWorkDuring not like", value, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringIn(List<String> values) {
            addCriterion("spWorkDuring in", values, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringNotIn(List<String> values) {
            addCriterion("spWorkDuring not in", values, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringBetween(String value1, String value2) {
            addCriterion("spWorkDuring between", value1, value2, "spworkduring");
            return this;
        }

        public Criteria andSpworkduringNotBetween(String value1, String value2) {
            addCriterion("spWorkDuring not between", value1, value2, "spworkduring");
            return this;
        }

        public Criteria andEducationenumidIsNull() {
            addCriterion("educationEnumId is null");
            return this;
        }

        public Criteria andEducationenumidIsNotNull() {
            addCriterion("educationEnumId is not null");
            return this;
        }

        public Criteria andEducationenumidEqualTo(String value) {
            addCriterion("educationEnumId =", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidNotEqualTo(String value) {
            addCriterion("educationEnumId <>", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidGreaterThan(String value) {
            addCriterion("educationEnumId >", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidGreaterThanOrEqualTo(String value) {
            addCriterion("educationEnumId >=", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidLessThan(String value) {
            addCriterion("educationEnumId <", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidLessThanOrEqualTo(String value) {
            addCriterion("educationEnumId <=", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidLike(String value) {
            addCriterion("educationEnumId like", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidNotLike(String value) {
            addCriterion("educationEnumId not like", value, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidIn(List<String> values) {
            addCriterion("educationEnumId in", values, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidNotIn(List<String> values) {
            addCriterion("educationEnumId not in", values, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidBetween(String value1, String value2) {
            addCriterion("educationEnumId between", value1, value2, "educationenumid");
            return this;
        }

        public Criteria andEducationenumidNotBetween(String value1, String value2) {
            addCriterion("educationEnumId not between", value1, value2, "educationenumid");
            return this;
        }

        public Criteria andMobilephoneIsNull() {
            addCriterion("mobilePhone is null");
            return this;
        }

        public Criteria andMobilephoneIsNotNull() {
            addCriterion("mobilePhone is not null");
            return this;
        }

        public Criteria andMobilephoneEqualTo(String value) {
            addCriterion("mobilePhone =", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneNotEqualTo(String value) {
            addCriterion("mobilePhone <>", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneGreaterThan(String value) {
            addCriterion("mobilePhone >", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneGreaterThanOrEqualTo(String value) {
            addCriterion("mobilePhone >=", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneLessThan(String value) {
            addCriterion("mobilePhone <", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneLessThanOrEqualTo(String value) {
            addCriterion("mobilePhone <=", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneLike(String value) {
            addCriterion("mobilePhone like", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneNotLike(String value) {
            addCriterion("mobilePhone not like", value, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneIn(List<String> values) {
            addCriterion("mobilePhone in", values, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneNotIn(List<String> values) {
            addCriterion("mobilePhone not in", values, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneBetween(String value1, String value2) {
            addCriterion("mobilePhone between", value1, value2, "mobilephone");
            return this;
        }

        public Criteria andMobilephoneNotBetween(String value1, String value2) {
            addCriterion("mobilePhone not between", value1, value2, "mobilephone");
            return this;
        }

        public Criteria andTeleIsNull() {
            addCriterion("tele is null");
            return this;
        }

        public Criteria andTeleIsNotNull() {
            addCriterion("tele is not null");
            return this;
        }

        public Criteria andTeleEqualTo(String value) {
            addCriterion("tele =", value, "tele");
            return this;
        }

        public Criteria andTeleNotEqualTo(String value) {
            addCriterion("tele <>", value, "tele");
            return this;
        }

        public Criteria andTeleGreaterThan(String value) {
            addCriterion("tele >", value, "tele");
            return this;
        }

        public Criteria andTeleGreaterThanOrEqualTo(String value) {
            addCriterion("tele >=", value, "tele");
            return this;
        }

        public Criteria andTeleLessThan(String value) {
            addCriterion("tele <", value, "tele");
            return this;
        }

        public Criteria andTeleLessThanOrEqualTo(String value) {
            addCriterion("tele <=", value, "tele");
            return this;
        }

        public Criteria andTeleLike(String value) {
            addCriterion("tele like", value, "tele");
            return this;
        }

        public Criteria andTeleNotLike(String value) {
            addCriterion("tele not like", value, "tele");
            return this;
        }

        public Criteria andTeleIn(List<String> values) {
            addCriterion("tele in", values, "tele");
            return this;
        }

        public Criteria andTeleNotIn(List<String> values) {
            addCriterion("tele not in", values, "tele");
            return this;
        }

        public Criteria andTeleBetween(String value1, String value2) {
            addCriterion("tele between", value1, value2, "tele");
            return this;
        }

        public Criteria andTeleNotBetween(String value1, String value2) {
            addCriterion("tele not between", value1, value2, "tele");
            return this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return this;
        }

        public Criteria andMajortitleIsNull() {
            addCriterion("majorTitle is null");
            return this;
        }

        public Criteria andMajortitleIsNotNull() {
            addCriterion("majorTitle is not null");
            return this;
        }

        public Criteria andMajortitleEqualTo(String value) {
            addCriterion("majorTitle =", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleNotEqualTo(String value) {
            addCriterion("majorTitle <>", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleGreaterThan(String value) {
            addCriterion("majorTitle >", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleGreaterThanOrEqualTo(String value) {
            addCriterion("majorTitle >=", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleLessThan(String value) {
            addCriterion("majorTitle <", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleLessThanOrEqualTo(String value) {
            addCriterion("majorTitle <=", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleLike(String value) {
            addCriterion("majorTitle like", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleNotLike(String value) {
            addCriterion("majorTitle not like", value, "majortitle");
            return this;
        }

        public Criteria andMajortitleIn(List<String> values) {
            addCriterion("majorTitle in", values, "majortitle");
            return this;
        }

        public Criteria andMajortitleNotIn(List<String> values) {
            addCriterion("majorTitle not in", values, "majortitle");
            return this;
        }

        public Criteria andMajortitleBetween(String value1, String value2) {
            addCriterion("majorTitle between", value1, value2, "majortitle");
            return this;
        }

        public Criteria andMajortitleNotBetween(String value1, String value2) {
            addCriterion("majorTitle not between", value1, value2, "majortitle");
            return this;
        }

        public Criteria andRequestlitigationIsNull() {
            addCriterion("requestLitigation is null");
            return this;
        }

        public Criteria andRequestlitigationIsNotNull() {
            addCriterion("requestLitigation is not null");
            return this;
        }

        public Criteria andRequestlitigationEqualTo(String value) {
            addCriterion("requestLitigation =", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationNotEqualTo(String value) {
            addCriterion("requestLitigation <>", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationGreaterThan(String value) {
            addCriterion("requestLitigation >", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationGreaterThanOrEqualTo(String value) {
            addCriterion("requestLitigation >=", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationLessThan(String value) {
            addCriterion("requestLitigation <", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationLessThanOrEqualTo(String value) {
            addCriterion("requestLitigation <=", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationLike(String value) {
            addCriterion("requestLitigation like", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationNotLike(String value) {
            addCriterion("requestLitigation not like", value, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationIn(List<String> values) {
            addCriterion("requestLitigation in", values, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationNotIn(List<String> values) {
            addCriterion("requestLitigation not in", values, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationBetween(String value1, String value2) {
            addCriterion("requestLitigation between", value1, value2, "requestlitigation");
            return this;
        }

        public Criteria andRequestlitigationNotBetween(String value1, String value2) {
            addCriterion("requestLitigation not between", value1, value2, "requestlitigation");
            return this;
        }

        public Criteria andCertificationpictureIsNull() {
            addCriterion("certificationPicture is null");
            return this;
        }

        public Criteria andCertificationpictureIsNotNull() {
            addCriterion("certificationPicture is not null");
            return this;
        }

        public Criteria andCertificationpictureEqualTo(String value) {
            addCriterion("certificationPicture =", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureNotEqualTo(String value) {
            addCriterion("certificationPicture <>", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureGreaterThan(String value) {
            addCriterion("certificationPicture >", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureGreaterThanOrEqualTo(String value) {
            addCriterion("certificationPicture >=", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureLessThan(String value) {
            addCriterion("certificationPicture <", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureLessThanOrEqualTo(String value) {
            addCriterion("certificationPicture <=", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureLike(String value) {
            addCriterion("certificationPicture like", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureNotLike(String value) {
            addCriterion("certificationPicture not like", value, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureIn(List<String> values) {
            addCriterion("certificationPicture in", values, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureNotIn(List<String> values) {
            addCriterion("certificationPicture not in", values, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureBetween(String value1, String value2) {
            addCriterion("certificationPicture between", value1, value2, "certificationpicture");
            return this;
        }

        public Criteria andCertificationpictureNotBetween(String value1, String value2) {
            addCriterion("certificationPicture not between", value1, value2, "certificationpicture");
            return this;
        }

        public Criteria andEnterpriseidIsNull() {
            addCriterion("enterpriseId is null");
            return this;
        }

        public Criteria andEnterpriseidIsNotNull() {
            addCriterion("enterpriseId is not null");
            return this;
        }

        public Criteria andEnterpriseidEqualTo(String value) {
            addCriterion("enterpriseId =", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidNotEqualTo(String value) {
            addCriterion("enterpriseId <>", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidGreaterThan(String value) {
            addCriterion("enterpriseId >", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidGreaterThanOrEqualTo(String value) {
            addCriterion("enterpriseId >=", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidLessThan(String value) {
            addCriterion("enterpriseId <", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidLessThanOrEqualTo(String value) {
            addCriterion("enterpriseId <=", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidLike(String value) {
            addCriterion("enterpriseId like", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidNotLike(String value) {
            addCriterion("enterpriseId not like", value, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidIn(List<String> values) {
            addCriterion("enterpriseId in", values, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidNotIn(List<String> values) {
            addCriterion("enterpriseId not in", values, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidBetween(String value1, String value2) {
            addCriterion("enterpriseId between", value1, value2, "enterpriseid");
            return this;
        }

        public Criteria andEnterpriseidNotBetween(String value1, String value2) {
            addCriterion("enterpriseId not between", value1, value2, "enterpriseid");
            return this;
        }

        public Criteria andRequesttypeidIsNull() {
            addCriterion("requestTypeId is null");
            return this;
        }

        public Criteria andRequesttypeidIsNotNull() {
            addCriterion("requestTypeId is not null");
            return this;
        }

        public Criteria andRequesttypeidEqualTo(String value) {
            addCriterion("requestTypeId =", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidNotEqualTo(String value) {
            addCriterion("requestTypeId <>", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidGreaterThan(String value) {
            addCriterion("requestTypeId >", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidGreaterThanOrEqualTo(String value) {
            addCriterion("requestTypeId >=", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidLessThan(String value) {
            addCriterion("requestTypeId <", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidLessThanOrEqualTo(String value) {
            addCriterion("requestTypeId <=", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidLike(String value) {
            addCriterion("requestTypeId like", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidNotLike(String value) {
            addCriterion("requestTypeId not like", value, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidIn(List<String> values) {
            addCriterion("requestTypeId in", values, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidNotIn(List<String> values) {
            addCriterion("requestTypeId not in", values, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidBetween(String value1, String value2) {
            addCriterion("requestTypeId between", value1, value2, "requesttypeid");
            return this;
        }

        public Criteria andRequesttypeidNotBetween(String value1, String value2) {
            addCriterion("requestTypeId not between", value1, value2, "requesttypeid");
            return this;
        }

        public Criteria andSelectresultenumidIsNull() {
            addCriterion("selectResultEnumId is null");
            return this;
        }

        public Criteria andSelectresultenumidIsNotNull() {
            addCriterion("selectResultEnumId is not null");
            return this;
        }

        public Criteria andSelectresultenumidEqualTo(String value) {
            addCriterion("selectResultEnumId =", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidNotEqualTo(String value) {
            addCriterion("selectResultEnumId <>", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidGreaterThan(String value) {
            addCriterion("selectResultEnumId >", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidGreaterThanOrEqualTo(String value) {
            addCriterion("selectResultEnumId >=", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidLessThan(String value) {
            addCriterion("selectResultEnumId <", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidLessThanOrEqualTo(String value) {
            addCriterion("selectResultEnumId <=", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidLike(String value) {
            addCriterion("selectResultEnumId like", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidNotLike(String value) {
            addCriterion("selectResultEnumId not like", value, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidIn(List<String> values) {
            addCriterion("selectResultEnumId in", values, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidNotIn(List<String> values) {
            addCriterion("selectResultEnumId not in", values, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidBetween(String value1, String value2) {
            addCriterion("selectResultEnumId between", value1, value2, "selectresultenumid");
            return this;
        }

        public Criteria andSelectresultenumidNotBetween(String value1, String value2) {
            addCriterion("selectResultEnumId not between", value1, value2, "selectresultenumid");
            return this;
        }

        public Criteria andScoreIsNull() {
            addCriterion("score is null");
            return this;
        }

        public Criteria andScoreIsNotNull() {
            addCriterion("score is not null");
            return this;
        }

        public Criteria andScoreEqualTo(String value) {
            addCriterion("score =", value, "score");
            return this;
        }

        public Criteria andScoreNotEqualTo(String value) {
            addCriterion("score <>", value, "score");
            return this;
        }

        public Criteria andScoreGreaterThan(String value) {
            addCriterion("score >", value, "score");
            return this;
        }

        public Criteria andScoreGreaterThanOrEqualTo(String value) {
            addCriterion("score >=", value, "score");
            return this;
        }

        public Criteria andScoreLessThan(String value) {
            addCriterion("score <", value, "score");
            return this;
        }

        public Criteria andScoreLessThanOrEqualTo(String value) {
            addCriterion("score <=", value, "score");
            return this;
        }

        public Criteria andScoreLike(String value) {
            addCriterion("score like", value, "score");
            return this;
        }

        public Criteria andScoreNotLike(String value) {
            addCriterion("score not like", value, "score");
            return this;
        }

        public Criteria andScoreIn(List<String> values) {
            addCriterion("score in", values, "score");
            return this;
        }

        public Criteria andScoreNotIn(List<String> values) {
            addCriterion("score not in", values, "score");
            return this;
        }

        public Criteria andScoreBetween(String value1, String value2) {
            addCriterion("score between", value1, value2, "score");
            return this;
        }

        public Criteria andScoreNotBetween(String value1, String value2) {
            addCriterion("score not between", value1, value2, "score");
            return this;
        }

        public Criteria andSelectremarkIsNull() {
            addCriterion("selectRemark is null");
            return this;
        }

        public Criteria andSelectremarkIsNotNull() {
            addCriterion("selectRemark is not null");
            return this;
        }

        public Criteria andSelectremarkEqualTo(String value) {
            addCriterion("selectRemark =", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkNotEqualTo(String value) {
            addCriterion("selectRemark <>", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkGreaterThan(String value) {
            addCriterion("selectRemark >", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkGreaterThanOrEqualTo(String value) {
            addCriterion("selectRemark >=", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkLessThan(String value) {
            addCriterion("selectRemark <", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkLessThanOrEqualTo(String value) {
            addCriterion("selectRemark <=", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkLike(String value) {
            addCriterion("selectRemark like", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkNotLike(String value) {
            addCriterion("selectRemark not like", value, "selectremark");
            return this;
        }

        public Criteria andSelectremarkIn(List<String> values) {
            addCriterion("selectRemark in", values, "selectremark");
            return this;
        }

        public Criteria andSelectremarkNotIn(List<String> values) {
            addCriterion("selectRemark not in", values, "selectremark");
            return this;
        }

        public Criteria andSelectremarkBetween(String value1, String value2) {
            addCriterion("selectRemark between", value1, value2, "selectremark");
            return this;
        }

        public Criteria andSelectremarkNotBetween(String value1, String value2) {
            addCriterion("selectRemark not between", value1, value2, "selectremark");
            return this;
        }

        public Criteria andSelectyearIsNull() {
            addCriterion("selectYear is null");
            return this;
        }

        public Criteria andSelectyearIsNotNull() {
            addCriterion("selectYear is not null");
            return this;
        }

        public Criteria andSelectyearEqualTo(String value) {
            addCriterion("selectYear =", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearNotEqualTo(String value) {
            addCriterion("selectYear <>", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearGreaterThan(String value) {
            addCriterion("selectYear >", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearGreaterThanOrEqualTo(String value) {
            addCriterion("selectYear >=", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearLessThan(String value) {
            addCriterion("selectYear <", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearLessThanOrEqualTo(String value) {
            addCriterion("selectYear <=", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearLike(String value) {
            addCriterion("selectYear like", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearNotLike(String value) {
            addCriterion("selectYear not like", value, "selectyear");
            return this;
        }

        public Criteria andSelectyearIn(List<String> values) {
            addCriterion("selectYear in", values, "selectyear");
            return this;
        }

        public Criteria andSelectyearNotIn(List<String> values) {
            addCriterion("selectYear not in", values, "selectyear");
            return this;
        }

        public Criteria andSelectyearBetween(String value1, String value2) {
            addCriterion("selectYear between", value1, value2, "selectyear");
            return this;
        }

        public Criteria andSelectyearNotBetween(String value1, String value2) {
            addCriterion("selectYear not between", value1, value2, "selectyear");
            return this;
        }
    }
}