package com.meidusa.demo.dal.model;

import com.meidusa.toolkit.dal.ibator.AbstractModel;

public class ExcellentSelection extends AbstractModel {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.id
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.enterpriseName
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String enterprisename;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.legalRepresentative
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String legalrepresentative;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.address
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String address;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.requestName
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String requestname;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.requestOld
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String requestold;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.position
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String position;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.spWorkDuring
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String spworkduring;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.educationEnumId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String educationenumid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.mobilePhone
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String mobilephone;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.tele
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String tele;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.picture
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String picture;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.majorTitle
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String majortitle;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.requestLitigation
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String requestlitigation;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.certificationPicture
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String certificationpicture;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.enterpriseId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String enterpriseid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.requestTypeId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String requesttypeid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.selectResultEnumId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String selectresultenumid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.score
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String score;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.selectRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String selectremark;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column excellentselection.selectYear
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    private String selectyear;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.id
     *
     * @return the value of excellentselection.id
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.id
     *
     * @param id the value for excellentselection.id
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.enterpriseName
     *
     * @return the value of excellentselection.enterpriseName
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.enterpriseName
     *
     * @param enterprisename the value for excellentselection.enterpriseName
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.legalRepresentative
     *
     * @return the value of excellentselection.legalRepresentative
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getLegalrepresentative() {
        return legalrepresentative;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.legalRepresentative
     *
     * @param legalrepresentative the value for excellentselection.legalRepresentative
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setLegalrepresentative(String legalrepresentative) {
        this.legalrepresentative = legalrepresentative;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.address
     *
     * @return the value of excellentselection.address
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.address
     *
     * @param address the value for excellentselection.address
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.requestName
     *
     * @return the value of excellentselection.requestName
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getRequestname() {
        return requestname;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.requestName
     *
     * @param requestname the value for excellentselection.requestName
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setRequestname(String requestname) {
        this.requestname = requestname;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.requestOld
     *
     * @return the value of excellentselection.requestOld
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getRequestold() {
        return requestold;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.requestOld
     *
     * @param requestold the value for excellentselection.requestOld
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setRequestold(String requestold) {
        this.requestold = requestold;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.position
     *
     * @return the value of excellentselection.position
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.position
     *
     * @param position the value for excellentselection.position
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.spWorkDuring
     *
     * @return the value of excellentselection.spWorkDuring
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getSpworkduring() {
        return spworkduring;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.spWorkDuring
     *
     * @param spworkduring the value for excellentselection.spWorkDuring
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setSpworkduring(String spworkduring) {
        this.spworkduring = spworkduring;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.educationEnumId
     *
     * @return the value of excellentselection.educationEnumId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getEducationenumid() {
        return educationenumid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.educationEnumId
     *
     * @param educationenumid the value for excellentselection.educationEnumId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setEducationenumid(String educationenumid) {
        this.educationenumid = educationenumid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.mobilePhone
     *
     * @return the value of excellentselection.mobilePhone
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getMobilephone() {
        return mobilephone;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.mobilePhone
     *
     * @param mobilephone the value for excellentselection.mobilePhone
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setMobilephone(String mobilephone) {
        this.mobilephone = mobilephone;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.tele
     *
     * @return the value of excellentselection.tele
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getTele() {
        return tele;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.tele
     *
     * @param tele the value for excellentselection.tele
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setTele(String tele) {
        this.tele = tele;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.picture
     *
     * @return the value of excellentselection.picture
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.picture
     *
     * @param picture the value for excellentselection.picture
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.majorTitle
     *
     * @return the value of excellentselection.majorTitle
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getMajortitle() {
        return majortitle;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.majorTitle
     *
     * @param majortitle the value for excellentselection.majorTitle
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setMajortitle(String majortitle) {
        this.majortitle = majortitle;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.requestLitigation
     *
     * @return the value of excellentselection.requestLitigation
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getRequestlitigation() {
        return requestlitigation;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.requestLitigation
     *
     * @param requestlitigation the value for excellentselection.requestLitigation
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setRequestlitigation(String requestlitigation) {
        this.requestlitigation = requestlitigation;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.certificationPicture
     *
     * @return the value of excellentselection.certificationPicture
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getCertificationpicture() {
        return certificationpicture;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.certificationPicture
     *
     * @param certificationpicture the value for excellentselection.certificationPicture
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setCertificationpicture(String certificationpicture) {
        this.certificationpicture = certificationpicture;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.enterpriseId
     *
     * @return the value of excellentselection.enterpriseId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getEnterpriseid() {
        return enterpriseid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.enterpriseId
     *
     * @param enterpriseid the value for excellentselection.enterpriseId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setEnterpriseid(String enterpriseid) {
        this.enterpriseid = enterpriseid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.requestTypeId
     *
     * @return the value of excellentselection.requestTypeId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getRequesttypeid() {
        return requesttypeid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.requestTypeId
     *
     * @param requesttypeid the value for excellentselection.requestTypeId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setRequesttypeid(String requesttypeid) {
        this.requesttypeid = requesttypeid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.selectResultEnumId
     *
     * @return the value of excellentselection.selectResultEnumId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getSelectresultenumid() {
        return selectresultenumid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.selectResultEnumId
     *
     * @param selectresultenumid the value for excellentselection.selectResultEnumId
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setSelectresultenumid(String selectresultenumid) {
        this.selectresultenumid = selectresultenumid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.score
     *
     * @return the value of excellentselection.score
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getScore() {
        return score;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.score
     *
     * @param score the value for excellentselection.score
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setScore(String score) {
        this.score = score;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.selectRemark
     *
     * @return the value of excellentselection.selectRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getSelectremark() {
        return selectremark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.selectRemark
     *
     * @param selectremark the value for excellentselection.selectRemark
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setSelectremark(String selectremark) {
        this.selectremark = selectremark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column excellentselection.selectYear
     *
     * @return the value of excellentselection.selectYear
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public String getSelectyear() {
        return selectyear;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column excellentselection.selectYear
     *
     * @param selectyear the value for excellentselection.selectYear
     *
     * @ibatorgenerated Sun Jun 27 08:14:47 CST 2010
     */
    public void setSelectyear(String selectyear) {
        this.selectyear = selectyear;
    }

    
    private String educationdesc;
    private String requesttypedesc;
    private String selectresultdesc;
    
	public String getEducationdesc() {
		return educationdesc;
	}

	public void setEducationdesc(String educationdesc) {
		this.educationdesc = educationdesc;
	}

	public String getRequesttypedesc() {
		return requesttypedesc;
	}

	public void setRequesttypedesc(String requesttypedesc) {
		this.requesttypedesc = requesttypedesc;
	}

	public String getSelectresultdesc() {
		return selectresultdesc;
	}

	public void setSelectresultdesc(String selectresultdesc) {
		this.selectresultdesc = selectresultdesc;
	}

	@Override
	public String getForeignKey() {
		return requestname;
	}

	@Override
	public String getPrimaryKey() {
		return id;
	}

	@Override
	public void setForeignKey(String arg0) {
		requestname = arg0;
	}

	@Override
	public void setPrimaryKey(String arg0) {
		id = arg0;
	}
}