package com.meidusa.demo.dal.model;

import com.meidusa.toolkit.dal.ibator.AbstractModel;
import java.util.Date;

public class Finance extends AbstractModel {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.id
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.financeTime
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private Date financetime;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.assets
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private Double assets;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.income
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private Double income;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.netProfit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private Double netprofit;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.netChainRatio
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private String netchainratio;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.netYearRatio
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private String netyearratio;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column finance.enterpriseid
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    private String enterpriseid;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.id
     *
     * @return the value of finance.id
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.id
     *
     * @param id the value for finance.id
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.financeTime
     *
     * @return the value of finance.financeTime
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Date getFinancetime() {
        return financetime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.financeTime
     *
     * @param financetime the value for finance.financeTime
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setFinancetime(Date financetime) {
        this.financetime = financetime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.assets
     *
     * @return the value of finance.assets
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Double getAssets() {
        return assets;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.assets
     *
     * @param assets the value for finance.assets
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setAssets(Double assets) {
        this.assets = assets;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.income
     *
     * @return the value of finance.income
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Double getIncome() {
        return income;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.income
     *
     * @param income the value for finance.income
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setIncome(Double income) {
        this.income = income;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.netProfit
     *
     * @return the value of finance.netProfit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Double getNetprofit() {
        return netprofit;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.netProfit
     *
     * @param netprofit the value for finance.netProfit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setNetprofit(Double netprofit) {
        this.netprofit = netprofit;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.netChainRatio
     *
     * @return the value of finance.netChainRatio
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public String getNetchainratio() {
        return netchainratio;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.netChainRatio
     *
     * @param netchainratio the value for finance.netChainRatio
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setNetchainratio(String netchainratio) {
        this.netchainratio = netchainratio;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.netYearRatio
     *
     * @return the value of finance.netYearRatio
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public String getNetyearratio() {
        return netyearratio;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.netYearRatio
     *
     * @param netyearratio the value for finance.netYearRatio
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setNetyearratio(String netyearratio) {
        this.netyearratio = netyearratio;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column finance.enterpriseid
     *
     * @return the value of finance.enterpriseid
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public String getEnterpriseid() {
        return enterpriseid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column finance.enterpriseid
     *
     * @param enterpriseid the value for finance.enterpriseid
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void setEnterpriseid(String enterpriseid) {
        this.enterpriseid = enterpriseid;
    }

	@Override
	public String getForeignKey() {
		return enterpriseid;
	}

	@Override
	public String getPrimaryKey() {
		return id;
	}

	@Override
	public void setForeignKey(String arg0) {
		enterpriseid = arg0;
	}

	@Override
	public void setPrimaryKey(String arg0) {
		id = arg0;
	}
}