package com.meidusa.demo.dal.model;

import com.meidusa.toolkit.dal.ibator.AbstractModel;
import java.util.Date;

public class SelfTechPerson extends AbstractModel {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.id
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.enterpriseName
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String enterprisename;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.businessType
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String businesstype;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.personName
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String personname;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.personSex
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String personsex;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.position
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String position;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.technicalTitle
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String technicaltitle;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.birthdate
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String birthdate;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.idCardNo
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String idcardno;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.securityNo
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String securityno;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.techExamCer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String techexamcer;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.remark
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private String remark;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column selftechperson.lastUpdateTime
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    private Date lastupdatetime;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.id
     *
     * @return the value of selftechperson.id
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.id
     *
     * @param id the value for selftechperson.id
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.enterpriseName
     *
     * @return the value of selftechperson.enterpriseName
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getEnterprisename() {
        return enterprisename;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.enterpriseName
     *
     * @param enterprisename the value for selftechperson.enterpriseName
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setEnterprisename(String enterprisename) {
        this.enterprisename = enterprisename;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.businessType
     *
     * @return the value of selftechperson.businessType
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.businessType
     *
     * @param businesstype the value for selftechperson.businessType
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.personName
     *
     * @return the value of selftechperson.personName
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getPersonname() {
        return personname;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.personName
     *
     * @param personname the value for selftechperson.personName
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setPersonname(String personname) {
        this.personname = personname;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.personSex
     *
     * @return the value of selftechperson.personSex
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getPersonsex() {
        return personsex;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.personSex
     *
     * @param personsex the value for selftechperson.personSex
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setPersonsex(String personsex) {
        this.personsex = personsex;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.position
     *
     * @return the value of selftechperson.position
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.position
     *
     * @param position the value for selftechperson.position
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setPosition(String position) {
        this.position = position;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.technicalTitle
     *
     * @return the value of selftechperson.technicalTitle
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getTechnicaltitle() {
        return technicaltitle;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.technicalTitle
     *
     * @param technicaltitle the value for selftechperson.technicalTitle
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setTechnicaltitle(String technicaltitle) {
        this.technicaltitle = technicaltitle;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.birthdate
     *
     * @return the value of selftechperson.birthdate
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getBirthdate() {
        return birthdate;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.birthdate
     *
     * @param birthdate the value for selftechperson.birthdate
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setBirthdate(String birthdate) {
        this.birthdate = birthdate;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.idCardNo
     *
     * @return the value of selftechperson.idCardNo
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getIdcardno() {
        return idcardno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.idCardNo
     *
     * @param idcardno the value for selftechperson.idCardNo
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setIdcardno(String idcardno) {
        this.idcardno = idcardno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.securityNo
     *
     * @return the value of selftechperson.securityNo
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getSecurityno() {
        return securityno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.securityNo
     *
     * @param securityno the value for selftechperson.securityNo
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setSecurityno(String securityno) {
        this.securityno = securityno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.techExamCer
     *
     * @return the value of selftechperson.techExamCer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getTechexamcer() {
        return techexamcer;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.techExamCer
     *
     * @param techexamcer the value for selftechperson.techExamCer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setTechexamcer(String techexamcer) {
        this.techexamcer = techexamcer;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.remark
     *
     * @return the value of selftechperson.remark
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.remark
     *
     * @param remark the value for selftechperson.remark
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column selftechperson.lastUpdateTime
     *
     * @return the value of selftechperson.lastUpdateTime
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public Date getLastupdatetime() {
        return lastupdatetime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column selftechperson.lastUpdateTime
     *
     * @param lastupdatetime the value for selftechperson.lastUpdateTime
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void setLastupdatetime(Date lastupdatetime) {
        this.lastupdatetime = lastupdatetime;
    }

	@Override
	public String getForeignKey() {
		return this.enterprisename;
	}

	@Override
	public String getPrimaryKey() {
		return this.id;
	}

	@Override
	public void setForeignKey(String arg0) {
		this.enterprisename = arg0;
	}

	@Override
	public void setPrimaryKey(String arg0) {
		this.id = arg0;
	}
}