package com.meidusa.demo.dal.model;

import com.meidusa.toolkit.dal.ibator.AbstractModel;
import java.util.Date;

public class VEnterpriseAllInfo extends AbstractModel {
    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.id
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String id;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.name
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String name;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.enrollTime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private Date enrolltime;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.withDrawtime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private Date withdrawtime;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.natureId
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String natureid;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.productBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String productbound;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.projectBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String projectbound;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.industryBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String industrybound;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.operationMode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String operationmode;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.businessType
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String businesstype;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.province
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String province;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.city
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String city;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.linkAddr
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String linkaddr;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.linkZipcode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String linkzipcode;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.legalPerson
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String legalperson;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.legalPersonCardNo
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String legalpersoncardno;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.contact
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String contact;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.contactCardNo
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String contactcardno;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.linkTel
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String linktel;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.linkFax
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String linkfax;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.linkEmail
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String linkemail;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.linkWebsite
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String linkwebsite;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.businessLicense
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String businesslicense;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.orgCode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String orgcode;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.requestLevel
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String requestlevel;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.requestCode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String requestcode;

    /**
     * This field was generated by Apache iBATIS Ibator.
     * This field corresponds to the database column venterpriseallinfo.requestTime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    private String requesttime;

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.id
     *
     * @return the value of venterpriseallinfo.id
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.id
     *
     * @param id the value for venterpriseallinfo.id
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setId(String id) {
        this.id = id;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.name
     *
     * @return the value of venterpriseallinfo.name
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.name
     *
     * @param name the value for venterpriseallinfo.name
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.enrollTime
     *
     * @return the value of venterpriseallinfo.enrollTime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public Date getEnrolltime() {
        return enrolltime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.enrollTime
     *
     * @param enrolltime the value for venterpriseallinfo.enrollTime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setEnrolltime(Date enrolltime) {
        this.enrolltime = enrolltime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.withDrawtime
     *
     * @return the value of venterpriseallinfo.withDrawtime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public Date getWithdrawtime() {
        return withdrawtime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.withDrawtime
     *
     * @param withdrawtime the value for venterpriseallinfo.withDrawtime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setWithdrawtime(Date withdrawtime) {
        this.withdrawtime = withdrawtime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.natureId
     *
     * @return the value of venterpriseallinfo.natureId
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getNatureid() {
        return natureid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.natureId
     *
     * @param natureid the value for venterpriseallinfo.natureId
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setNatureid(String natureid) {
        this.natureid = natureid;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.productBound
     *
     * @return the value of venterpriseallinfo.productBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getProductbound() {
        return productbound;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.productBound
     *
     * @param productbound the value for venterpriseallinfo.productBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setProductbound(String productbound) {
        this.productbound = productbound;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.projectBound
     *
     * @return the value of venterpriseallinfo.projectBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getProjectbound() {
        return projectbound;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.projectBound
     *
     * @param projectbound the value for venterpriseallinfo.projectBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setProjectbound(String projectbound) {
        this.projectbound = projectbound;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.industryBound
     *
     * @return the value of venterpriseallinfo.industryBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getIndustrybound() {
        return industrybound;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.industryBound
     *
     * @param industrybound the value for venterpriseallinfo.industryBound
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setIndustrybound(String industrybound) {
        this.industrybound = industrybound;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.operationMode
     *
     * @return the value of venterpriseallinfo.operationMode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getOperationmode() {
        return operationmode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.operationMode
     *
     * @param operationmode the value for venterpriseallinfo.operationMode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setOperationmode(String operationmode) {
        this.operationmode = operationmode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.businessType
     *
     * @return the value of venterpriseallinfo.businessType
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getBusinesstype() {
        return businesstype;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.businessType
     *
     * @param businesstype the value for venterpriseallinfo.businessType
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setBusinesstype(String businesstype) {
        this.businesstype = businesstype;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.province
     *
     * @return the value of venterpriseallinfo.province
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.province
     *
     * @param province the value for venterpriseallinfo.province
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setProvince(String province) {
        this.province = province;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.city
     *
     * @return the value of venterpriseallinfo.city
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.city
     *
     * @param city the value for venterpriseallinfo.city
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.linkAddr
     *
     * @return the value of venterpriseallinfo.linkAddr
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLinkaddr() {
        return linkaddr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.linkAddr
     *
     * @param linkaddr the value for venterpriseallinfo.linkAddr
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLinkaddr(String linkaddr) {
        this.linkaddr = linkaddr;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.linkZipcode
     *
     * @return the value of venterpriseallinfo.linkZipcode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLinkzipcode() {
        return linkzipcode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.linkZipcode
     *
     * @param linkzipcode the value for venterpriseallinfo.linkZipcode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLinkzipcode(String linkzipcode) {
        this.linkzipcode = linkzipcode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.legalPerson
     *
     * @return the value of venterpriseallinfo.legalPerson
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLegalperson() {
        return legalperson;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.legalPerson
     *
     * @param legalperson the value for venterpriseallinfo.legalPerson
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLegalperson(String legalperson) {
        this.legalperson = legalperson;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.legalPersonCardNo
     *
     * @return the value of venterpriseallinfo.legalPersonCardNo
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLegalpersoncardno() {
        return legalpersoncardno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.legalPersonCardNo
     *
     * @param legalpersoncardno the value for venterpriseallinfo.legalPersonCardNo
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLegalpersoncardno(String legalpersoncardno) {
        this.legalpersoncardno = legalpersoncardno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.contact
     *
     * @return the value of venterpriseallinfo.contact
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.contact
     *
     * @param contact the value for venterpriseallinfo.contact
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.contactCardNo
     *
     * @return the value of venterpriseallinfo.contactCardNo
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getContactcardno() {
        return contactcardno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.contactCardNo
     *
     * @param contactcardno the value for venterpriseallinfo.contactCardNo
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setContactcardno(String contactcardno) {
        this.contactcardno = contactcardno;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.linkTel
     *
     * @return the value of venterpriseallinfo.linkTel
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLinktel() {
        return linktel;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.linkTel
     *
     * @param linktel the value for venterpriseallinfo.linkTel
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLinktel(String linktel) {
        this.linktel = linktel;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.linkFax
     *
     * @return the value of venterpriseallinfo.linkFax
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLinkfax() {
        return linkfax;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.linkFax
     *
     * @param linkfax the value for venterpriseallinfo.linkFax
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLinkfax(String linkfax) {
        this.linkfax = linkfax;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.linkEmail
     *
     * @return the value of venterpriseallinfo.linkEmail
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLinkemail() {
        return linkemail;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.linkEmail
     *
     * @param linkemail the value for venterpriseallinfo.linkEmail
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLinkemail(String linkemail) {
        this.linkemail = linkemail;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.linkWebsite
     *
     * @return the value of venterpriseallinfo.linkWebsite
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getLinkwebsite() {
        return linkwebsite;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.linkWebsite
     *
     * @param linkwebsite the value for venterpriseallinfo.linkWebsite
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setLinkwebsite(String linkwebsite) {
        this.linkwebsite = linkwebsite;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.businessLicense
     *
     * @return the value of venterpriseallinfo.businessLicense
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getBusinesslicense() {
        return businesslicense;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.businessLicense
     *
     * @param businesslicense the value for venterpriseallinfo.businessLicense
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setBusinesslicense(String businesslicense) {
        this.businesslicense = businesslicense;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.orgCode
     *
     * @return the value of venterpriseallinfo.orgCode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getOrgcode() {
        return orgcode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.orgCode
     *
     * @param orgcode the value for venterpriseallinfo.orgCode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setOrgcode(String orgcode) {
        this.orgcode = orgcode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.requestLevel
     *
     * @return the value of venterpriseallinfo.requestLevel
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getRequestlevel() {
        return requestlevel;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.requestLevel
     *
     * @param requestlevel the value for venterpriseallinfo.requestLevel
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setRequestlevel(String requestlevel) {
        this.requestlevel = requestlevel;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.requestCode
     *
     * @return the value of venterpriseallinfo.requestCode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getRequestcode() {
        return requestcode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.requestCode
     *
     * @param requestcode the value for venterpriseallinfo.requestCode
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setRequestcode(String requestcode) {
        this.requestcode = requestcode;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method returns the value of the database column venterpriseallinfo.requestTime
     *
     * @return the value of venterpriseallinfo.requestTime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public String getRequesttime() {
        return requesttime;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method sets the value of the database column venterpriseallinfo.requestTime
     *
     * @param requesttime the value for venterpriseallinfo.requestTime
     *
     * @ibatorgenerated Tue Jun 18 15:42:45 CST 2013
     */
    public void setRequesttime(String requesttime) {
        this.requesttime = requesttime;
    }

	@Override
	public String getForeignKey() {
		return this.name;
	}

	@Override
	public String getPrimaryKey() {
		return this.id;
	}

	@Override
	public void setForeignKey(String arg0) {
		this.name = arg0;
	}

	@Override
	public void setPrimaryKey(String arg0) {
		this.id = arg0;
	}
}