package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Business;
import com.meidusa.demo.dal.model.BusinessExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface BusinessDAO extends AbstractDAO<Business, BusinessExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(BusinessExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(BusinessExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(Business record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(Business record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<Business> selectByExample(BusinessExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    Business selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(Business record, BusinessExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExample(Business record, BusinessExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(Business record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKey(Business record);
}