package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Business;
import com.meidusa.demo.dal.model.BusinessExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class BusinessDAOImpl extends SqlMapClientDaoSupport implements BusinessDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public BusinessDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(BusinessExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("business.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(BusinessExample example) {
        int rows = getSqlMapClientTemplate().delete("business.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        Business key = new Business();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("business.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(Business record) {
        getSqlMapClientTemplate().insert("business.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(Business record) {
        getSqlMapClientTemplate().insert("business.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Business> selectByExample(BusinessExample example) {
        List<Business> list = getSqlMapClientTemplate().queryForList("business.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Business selectByPrimaryKey(String id) {
        Business key = new Business();
        key.setId(id);
        Business record = (Business) getSqlMapClientTemplate().queryForObject("business.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(Business record, BusinessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("business.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(Business record, BusinessExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("business.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(Business record) {
        int rows = getSqlMapClientTemplate().update("business.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(Business record) {
        int rows = getSqlMapClientTemplate().update("business.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table business
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends BusinessExample {
        private Object record;

        public UpdateByExampleParms(Object record, BusinessExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<Business> selectByExampleWithBLOBs(BusinessExample arg0) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Business> selectByExampleWithoutBLOBs(BusinessExample arg0) {
        List<Business> list = getSqlMapClientTemplate().queryForList("business.selectByExample", arg0);
        return list;
	}

	public int updateByExampleWithBLOBs(Business arg0, BusinessExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(Business arg0, BusinessExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(Business arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(Business arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}