package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.CandidateTrains;
import com.meidusa.demo.dal.model.CandidateTrainsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CandidateTrainsDAOImpl extends SqlMapClientDaoSupport implements
		CandidateTrainsDAO {

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public CandidateTrainsDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int countByExample(CandidateTrainsExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"candidatetrains.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int deleteByExample(CandidateTrainsExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"candidatetrains.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		CandidateTrains key = new CandidateTrains();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"candidatetrains.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public void insert(CandidateTrains record) {
		getSqlMapClientTemplate().insert("candidatetrains.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public void insertSelective(CandidateTrains record) {
		getSqlMapClientTemplate().insert("candidatetrains.insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<CandidateTrains> selectByExample(CandidateTrainsExample example) {
		List<CandidateTrains> list = getSqlMapClientTemplate().queryForList(
				"candidatetrains.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public CandidateTrains selectByPrimaryKey(String id) {
		CandidateTrains key = new CandidateTrains();
		key.setId(id);
		CandidateTrains record = (CandidateTrains) getSqlMapClientTemplate()
				.queryForObject("candidatetrains.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int updateByExampleSelective(CandidateTrains record,
			CandidateTrainsExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"candidatetrains.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int updateByExample(CandidateTrains record,
			CandidateTrainsExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"candidatetrains.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int updateByPrimaryKeySelective(CandidateTrains record) {
		int rows = getSqlMapClientTemplate().update(
				"candidatetrains.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method
	 * corresponds to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	public int updateByPrimaryKey(CandidateTrains record) {
		int rows = getSqlMapClientTemplate().update(
				"candidatetrains.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS Ibator. This class corresponds
	 * to the database table candidatetrains
	 * 
	 * @ibatorgenerated Tue May 04 11:41:32 CST 2010
	 */
	protected static class UpdateByExampleParms extends CandidateTrainsExample {
		private Object record;

		public UpdateByExampleParms(Object record,
				CandidateTrainsExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
	public List<CandidateTrains> selectByExampleWithBLOBs(
			CandidateTrainsExample example) {
		List<CandidateTrains> list = getSqlMapClientTemplate().queryForList(
				"candidatetrains.selectByExample", example);
		return list;
	}

	@SuppressWarnings("unchecked")
	public List<CandidateTrains> selectByExampleWithoutBLOBs(
			CandidateTrainsExample example) {
		List<CandidateTrains> list = getSqlMapClientTemplate().queryForList(
				"candidatetrains.selectByExample", example);
		return list;
	}

	public int updateByExampleWithBLOBs(CandidateTrains arg0,
			CandidateTrainsExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(CandidateTrains arg0,
			CandidateTrainsExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(CandidateTrains arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(CandidateTrains arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@SuppressWarnings("unchecked")
	public List<CandidateTrains> statisticByAll(CandidateTrains record) {
		List<CandidateTrains> list = getSqlMapClientTemplate().queryForList(
				"candidatetrains.statisticByAll", record);
		return list;
	}
}