package com.meidusa.demo.dal;

import java.util.List;

import com.meidusa.demo.dal.model.CandidateTrains;
import com.meidusa.demo.dal.model.CandidateTrainsExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;

public interface CandidateTrainsDAO extends AbstractDAO<CandidateTrains, CandidateTrainsExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(CandidateTrainsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(CandidateTrainsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(CandidateTrains record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(CandidateTrains record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<CandidateTrains> selectByExample(CandidateTrainsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    CandidateTrains selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(CandidateTrains record, CandidateTrainsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExample(CandidateTrains record, CandidateTrainsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(CandidateTrains record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidatetrains
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKey(CandidateTrains record);
    
    
    List<CandidateTrains> statisticByAll(CandidateTrains record);
}