package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Candidates;
import com.meidusa.demo.dal.model.CandidatesExample;
import com.meidusa.demo.dal.model.CandidatesWithBLOBs;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class CandidatesDAOImpl extends SqlMapClientDaoSupport implements CandidatesDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public CandidatesDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(CandidatesExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("candidates.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(CandidatesExample example) {
        int rows = getSqlMapClientTemplate().delete("candidates.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        Candidates key = new Candidates();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("candidates.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(CandidatesWithBLOBs record) {
        getSqlMapClientTemplate().insert("candidates.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(CandidatesWithBLOBs record) {
        getSqlMapClientTemplate().insert("candidates.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<CandidatesWithBLOBs> selectByExampleWithBLOBs(CandidatesExample example) {
        List<CandidatesWithBLOBs> list = getSqlMapClientTemplate().queryForList("candidates.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<CandidatesWithBLOBs> selectByExampleWithoutBLOBs(CandidatesExample example) {
        List<CandidatesWithBLOBs> list = getSqlMapClientTemplate().queryForList("candidates.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public CandidatesWithBLOBs selectByPrimaryKey(String id) {
        Candidates key = new Candidates();
        key.setId(id);
        CandidatesWithBLOBs record = (CandidatesWithBLOBs) getSqlMapClientTemplate().queryForObject("candidates.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(CandidatesWithBLOBs record, CandidatesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("candidates.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(CandidatesWithBLOBs record, CandidatesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("candidates.updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(Candidates record, CandidatesExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("candidates.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(CandidatesWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("candidates.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(CandidatesWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("candidates.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(Candidates record) {
        int rows = getSqlMapClientTemplate().update("candidates.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table candidates
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends CandidatesExample {
        private Object record;

        public UpdateByExampleParms(Object record, CandidatesExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public int updateByExampleWithBLOBs(CandidatesWithBLOBs arg0,
			CandidatesExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(CandidatesWithBLOBs arg0,
			CandidatesExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(CandidatesWithBLOBs arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(CandidatesWithBLOBs arg0) {
		// TODO Auto-generated method stub
		return 0;
	}


}