package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.EnterpriseInfo;
import com.meidusa.demo.dal.model.EnterpriseInfoExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface EnterpriseInfoDAO extends AbstractDAO<EnterpriseInfo, EnterpriseInfoExample> {
    /**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int countByExample(EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int deleteByExample(EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	void insert(EnterpriseInfo record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	void insertSelective(EnterpriseInfo record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	List<EnterpriseInfo> selectByExampleWithBLOBs(EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	List<EnterpriseInfo> selectByExampleWithoutBLOBs(
			EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	EnterpriseInfo selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int updateByExampleSelective(EnterpriseInfo record,
			EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int updateByExampleWithBLOBs(EnterpriseInfo record,
			EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int updateByExampleWithoutBLOBs(EnterpriseInfo record,
			EnterpriseInfoExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int updateByPrimaryKeySelective(EnterpriseInfo record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int updateByPrimaryKeyWithBLOBs(EnterpriseInfo record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	int updateByPrimaryKeyWithoutBLOBs(EnterpriseInfo record);

	List<EnterpriseInfo> statisticBySelective(EnterpriseInfo record);
    
    List<EnterpriseInfo> statisticByAll(EnterpriseInfo record);
    
}