package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.EnterpriseInfo;
import com.meidusa.demo.dal.model.EnterpriseInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnterpriseInfoDAOImpl extends SqlMapClientDaoSupport implements EnterpriseInfoDAO {

    /**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public EnterpriseInfoDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int countByExample(EnterpriseInfoExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"enterpriseinfo.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int deleteByExample(EnterpriseInfoExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"enterpriseinfo.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		EnterpriseInfo key = new EnterpriseInfo();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"enterpriseinfo.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void insert(EnterpriseInfo record) {
		getSqlMapClientTemplate().insert("enterpriseinfo.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public void insertSelective(EnterpriseInfo record) {
		getSqlMapClientTemplate().insert("enterpriseinfo.insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<EnterpriseInfo> selectByExampleWithBLOBs(
			EnterpriseInfoExample example) {
		logger.debug("enterprise select debug with blobs,--------------");
		List<EnterpriseInfo> list = getSqlMapClientTemplate().queryForList(
				"enterpriseinfo.selectByExampleWithBLOBs", example);
		if(list != null){
			logger.debug("enterprise select debug with blobs,size--->"+list.size());
		}
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<EnterpriseInfo> selectByExampleWithoutBLOBs(
			EnterpriseInfoExample example) {
		logger.debug("enterprise select debug without blobs,--------------");
		List<EnterpriseInfo> list = getSqlMapClientTemplate().queryForList(
				"enterpriseinfo.selectByExample", example);
		if(list != null){
			logger.debug("enterprise select debug without blobs,size--->"+list.size());
		}
		
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public EnterpriseInfo selectByPrimaryKey(String id) {
		EnterpriseInfo key = new EnterpriseInfo();
		key.setId(id);
		EnterpriseInfo record = (EnterpriseInfo) getSqlMapClientTemplate()
				.queryForObject("enterpriseinfo.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int updateByExampleSelective(EnterpriseInfo record,
			EnterpriseInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"enterpriseinfo.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int updateByExampleWithBLOBs(EnterpriseInfo record,
			EnterpriseInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"enterpriseinfo.updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int updateByExampleWithoutBLOBs(EnterpriseInfo record,
			EnterpriseInfoExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"enterpriseinfo.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int updateByPrimaryKeySelective(EnterpriseInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"enterpriseinfo.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int updateByPrimaryKeyWithBLOBs(EnterpriseInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"enterpriseinfo.updateByPrimaryKeyWithBLOBs", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	public int updateByPrimaryKeyWithoutBLOBs(EnterpriseInfo record) {
		int rows = getSqlMapClientTemplate().update(
				"enterpriseinfo.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS Ibator. This class corresponds to the database table enterpriseinfo
	 * @ibatorgenerated  Sat Jul 10 10:53:55 CST 2010
	 */
	protected static class UpdateByExampleParms extends EnterpriseInfoExample {
		private Object record;

		public UpdateByExampleParms(Object record, EnterpriseInfoExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	@SuppressWarnings("unchecked")
	public List<EnterpriseInfo> statisticByAll(EnterpriseInfo record) {
        List<EnterpriseInfo> list = getSqlMapClientTemplate().queryForList("enterpriseinfo.statisticByAll", record);
        return list;
	}

	@SuppressWarnings("unchecked")
	public List<EnterpriseInfo> statisticBySelective(EnterpriseInfo record) {
        List<EnterpriseInfo> list = getSqlMapClientTemplate().queryForList("enterpriseinfo.statisticBySelective", record);
        return list;
	}
}