package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.EnterpriseCredit;
import com.meidusa.demo.dal.model.EnterpriseCreditExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnterpriseCreditDAOImpl extends SqlMapClientDaoSupport implements EnterpriseCreditDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public EnterpriseCreditDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(EnterpriseCreditExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("enterprisecredit.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(EnterpriseCreditExample example) {
        int rows = getSqlMapClientTemplate().delete("enterprisecredit.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        EnterpriseCredit key = new EnterpriseCredit();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("enterprisecredit.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(EnterpriseCredit record) {
        getSqlMapClientTemplate().insert("enterprisecredit.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(EnterpriseCredit record) {
        getSqlMapClientTemplate().insert("enterprisecredit.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<EnterpriseCredit> selectByExampleWithBLOBs(EnterpriseCreditExample example) {
        List<EnterpriseCredit> list = getSqlMapClientTemplate().queryForList("enterprisecredit.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<EnterpriseCredit> selectByExampleWithoutBLOBs(EnterpriseCreditExample example) {
        List<EnterpriseCredit> list = getSqlMapClientTemplate().queryForList("enterprisecredit.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public EnterpriseCredit selectByPrimaryKey(String id) {
        EnterpriseCredit key = new EnterpriseCredit();
        key.setId(id);
        EnterpriseCredit record = (EnterpriseCredit) getSqlMapClientTemplate().queryForObject("enterprisecredit.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(EnterpriseCredit record, EnterpriseCreditExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("enterprisecredit.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleWithBLOBs(EnterpriseCredit record, EnterpriseCreditExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("enterprisecredit.updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleWithoutBLOBs(EnterpriseCredit record, EnterpriseCreditExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("enterprisecredit.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(EnterpriseCredit record) {
        int rows = getSqlMapClientTemplate().update("enterprisecredit.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(EnterpriseCredit record) {
        int rows = getSqlMapClientTemplate().update("enterprisecredit.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(EnterpriseCredit record) {
        int rows = getSqlMapClientTemplate().update("enterprisecredit.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends EnterpriseCreditExample {
        private Object record;

        public UpdateByExampleParms(Object record, EnterpriseCreditExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}