package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.EnterpriseProducts;
import com.meidusa.demo.dal.model.EnterpriseProductsExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface EnterpriseProductsDAO extends AbstractDAO<EnterpriseProducts, EnterpriseProductsExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(EnterpriseProductsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(EnterpriseProductsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(EnterpriseProducts record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(EnterpriseProducts record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<EnterpriseProducts> selectByExample(EnterpriseProductsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    EnterpriseProducts selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(EnterpriseProducts record, EnterpriseProductsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExample(EnterpriseProducts record, EnterpriseProductsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(EnterpriseProducts record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKey(EnterpriseProducts record);
}