package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.EnterpriseProducts;
import com.meidusa.demo.dal.model.EnterpriseProductsExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnterpriseProductsDAOImpl extends SqlMapClientDaoSupport implements EnterpriseProductsDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public EnterpriseProductsDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(EnterpriseProductsExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("enterpriseproducts.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(EnterpriseProductsExample example) {
        int rows = getSqlMapClientTemplate().delete("enterpriseproducts.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        EnterpriseProducts key = new EnterpriseProducts();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("enterpriseproducts.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(EnterpriseProducts record) {
        getSqlMapClientTemplate().insert("enterpriseproducts.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(EnterpriseProducts record) {
        getSqlMapClientTemplate().insert("enterpriseproducts.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<EnterpriseProducts> selectByExample(EnterpriseProductsExample example) {
        List<EnterpriseProducts> list = getSqlMapClientTemplate().queryForList("enterpriseproducts.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public EnterpriseProducts selectByPrimaryKey(String id) {
        EnterpriseProducts key = new EnterpriseProducts();
        key.setId(id);
        EnterpriseProducts record = (EnterpriseProducts) getSqlMapClientTemplate().queryForObject("enterpriseproducts.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(EnterpriseProducts record, EnterpriseProductsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("enterpriseproducts.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(EnterpriseProducts record, EnterpriseProductsExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("enterpriseproducts.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(EnterpriseProducts record) {
        int rows = getSqlMapClientTemplate().update("enterpriseproducts.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(EnterpriseProducts record) {
        int rows = getSqlMapClientTemplate().update("enterpriseproducts.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table enterpriseproducts
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends EnterpriseProductsExample {
        private Object record;

        public UpdateByExampleParms(Object record, EnterpriseProductsExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<EnterpriseProducts> selectByExampleWithBLOBs(
			EnterpriseProductsExample arg0) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<EnterpriseProducts> selectByExampleWithoutBLOBs(
			EnterpriseProductsExample arg0) {
		// TODO Auto-generated method stub
		return null;
	}

	public int updateByExampleWithBLOBs(EnterpriseProducts arg0,
			EnterpriseProductsExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(EnterpriseProducts arg0,
			EnterpriseProductsExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(EnterpriseProducts arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(EnterpriseProducts arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}