package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.EnterpriseCredit;
import com.meidusa.demo.dal.model.EnterpriseCreditExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface EnterpriseCreditDAO extends AbstractDAO<EnterpriseCredit, EnterpriseCreditExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(EnterpriseCredit record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(EnterpriseCredit record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<EnterpriseCredit> selectByExampleWithBLOBs(EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<EnterpriseCredit> selectByExampleWithoutBLOBs(EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    EnterpriseCredit selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(EnterpriseCredit record, EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleWithBLOBs(EnterpriseCredit record, EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleWithoutBLOBs(EnterpriseCredit record, EnterpriseCreditExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(EnterpriseCredit record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(EnterpriseCredit record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table enterprisecredit
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(EnterpriseCredit record);
}