package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Enumeration;
import com.meidusa.demo.dal.model.EnumerationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class EnumerationDAOImpl extends SqlMapClientDaoSupport implements EnumerationDAO {

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public EnumerationDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int countByExample(EnumerationExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"enumeration.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int deleteByExample(EnumerationExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"enumeration.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int deleteByPrimaryKey(String enumid) {
		Enumeration key = new Enumeration();
		key.setEnumid(enumid);
		int rows = getSqlMapClientTemplate().delete(
				"enumeration.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public void insert(Enumeration record) {
		getSqlMapClientTemplate().insert("enumeration.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public void insertSelective(Enumeration record) {
		getSqlMapClientTemplate().insert("enumeration.insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Enumeration> selectByExample(EnumerationExample example) {
		List<Enumeration> list = getSqlMapClientTemplate().queryForList(
				"enumeration.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public Enumeration selectByPrimaryKey(String enumid) {
		Enumeration key = new Enumeration();
		key.setEnumid(enumid);
		Enumeration record = (Enumeration) getSqlMapClientTemplate()
				.queryForObject("enumeration.selectByPrimaryKey", key);
		return record;
	}
	
	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByExampleSelective(Enumeration record,
			EnumerationExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"enumeration.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByExample(Enumeration record, EnumerationExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"enumeration.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByPrimaryKeySelective(Enumeration record) {
		int rows = getSqlMapClientTemplate().update(
				"enumeration.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByPrimaryKey(Enumeration record) {
		int rows = getSqlMapClientTemplate().update(
				"enumeration.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS Ibator. This class corresponds to the database table enumeration
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	protected static class UpdateByExampleParms extends EnumerationExample {
		private Object record;

		public UpdateByExampleParms(Object record, EnumerationExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	public List<Enumeration> selectByExampleWithBLOBs(EnumerationExample arg0) {
		// TODO Auto-generated method stub
		return null;
	}

	public List<Enumeration> selectByExampleWithoutBLOBs(EnumerationExample arg0) {
		List<Enumeration> list = getSqlMapClientTemplate().queryForList(
				"enumeration.selectByExample", arg0);
		return list;
	}

	public int updateByExampleWithBLOBs(Enumeration arg0,
			EnumerationExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(Enumeration arg0,
			EnumerationExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(Enumeration arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(Enumeration arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}