package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Examination;
import com.meidusa.demo.dal.model.ExaminationExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface ExaminationDAO extends AbstractDAO<Examination, ExaminationExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int countByExample(ExaminationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int deleteByExample(ExaminationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    void insert(Examination record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    void insertSelective(Examination record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    List<Examination> selectByExample(ExaminationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    Examination selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByExampleSelective(Examination record, ExaminationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByExample(Examination record, ExaminationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByPrimaryKeySelective(Examination record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examination
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByPrimaryKey(Examination record);
}