package com.meidusa.demo.dal;

import java.util.List;

import com.meidusa.demo.dal.model.ExamEnrolls;
import com.meidusa.demo.dal.model.ExamEnrollsExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;

public interface ExamEnrollsDAO extends AbstractDAO<ExamEnrolls, ExamEnrollsExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:00 CST 2010
     */
    int countByExample(ExamEnrollsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:00 CST 2010
     */
    int deleteByExample(ExamEnrollsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:00 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:00 CST 2010
     */
    void insert(ExamEnrolls record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:00 CST 2010
     */
    void insertSelective(ExamEnrolls record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:00 CST 2010
     */
    List<ExamEnrolls> selectByExample(ExamEnrollsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:01 CST 2010
     */
    ExamEnrolls selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:01 CST 2010
     */
    int updateByExampleSelective(ExamEnrolls record, ExamEnrollsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:01 CST 2010
     */
    int updateByExample(ExamEnrolls record, ExamEnrollsExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:01 CST 2010
     */
    int updateByPrimaryKeySelective(ExamEnrolls record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table examenrolls
     *
     * @ibatorgenerated Wed May 05 21:15:01 CST 2010
     */
    int updateByPrimaryKey(ExamEnrolls record);
    
    List<ExamEnrolls> statisticByAll(ExamEnrolls record);
}