package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.ExpertProject;
import com.meidusa.demo.dal.model.ExpertProjectExample;
import com.meidusa.demo.dal.model.ExpertProjectWithBLOBs;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ExpertProjectDAOImpl extends SqlMapClientDaoSupport implements ExpertProjectDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public ExpertProjectDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int countByExample(ExpertProjectExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("expertproject.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int deleteByExample(ExpertProjectExample example) {
        int rows = getSqlMapClientTemplate().delete("expertproject.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        ExpertProject key = new ExpertProject();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("expertproject.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public void insert(ExpertProjectWithBLOBs record) {
        getSqlMapClientTemplate().insert("expertproject.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public void insertSelective(ExpertProjectWithBLOBs record) {
        getSqlMapClientTemplate().insert("expertproject.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<ExpertProjectWithBLOBs> selectByExampleWithBLOBs(ExpertProjectExample example) {
        List<ExpertProjectWithBLOBs> list = getSqlMapClientTemplate().queryForList("expertproject.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<ExpertProjectWithBLOBs> selectByExampleWithoutBLOBs(ExpertProjectExample example) {
        List<ExpertProjectWithBLOBs> list = getSqlMapClientTemplate().queryForList("expertproject.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public ExpertProjectWithBLOBs selectByPrimaryKey(String id) {
        ExpertProject key = new ExpertProject();
        key.setId(id);
        ExpertProjectWithBLOBs record = (ExpertProjectWithBLOBs) getSqlMapClientTemplate().queryForObject("expertproject.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int updateByExampleSelective(ExpertProjectWithBLOBs record, ExpertProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("expertproject.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int updateByExample(ExpertProjectWithBLOBs record, ExpertProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("expertproject.updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int updateByExample(ExpertProject record, ExpertProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("expertproject.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int updateByPrimaryKeySelective(ExpertProjectWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("expertproject.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int updateByPrimaryKey(ExpertProjectWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("expertproject.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    public int updateByPrimaryKey(ExpertProject record) {
        int rows = getSqlMapClientTemplate().update("expertproject.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table expertproject
     *
     * @ibatorgenerated Sat Jul 10 10:55:45 CST 2010
     */
    protected static class UpdateByExampleParms extends ExpertProjectExample {
        private Object record;

        public UpdateByExampleParms(Object record, ExpertProjectExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public int updateByExampleWithBLOBs(ExpertProjectWithBLOBs arg0,
			ExpertProjectExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(ExpertProjectWithBLOBs arg0,
			ExpertProjectExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(ExpertProjectWithBLOBs arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(ExpertProjectWithBLOBs arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}