package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Finance;
import com.meidusa.demo.dal.model.FinanceExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class FinanceDAOImpl extends SqlMapClientDaoSupport implements FinanceDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public FinanceDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(FinanceExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("finance.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(FinanceExample example) {
        int rows = getSqlMapClientTemplate().delete("finance.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        Finance key = new Finance();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("finance.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(Finance record) {
        getSqlMapClientTemplate().insert("finance.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(Finance record) {
        getSqlMapClientTemplate().insert("finance.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Finance> selectByExample(FinanceExample example) {
        List<Finance> list = getSqlMapClientTemplate().queryForList("finance.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Finance selectByPrimaryKey(String id) {
        Finance key = new Finance();
        key.setId(id);
        Finance record = (Finance) getSqlMapClientTemplate().queryForObject("finance.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(Finance record, FinanceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("finance.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(Finance record, FinanceExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("finance.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(Finance record) {
        int rows = getSqlMapClientTemplate().update("finance.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(Finance record) {
        int rows = getSqlMapClientTemplate().update("finance.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table finance
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends FinanceExample {
        private Object record;

        public UpdateByExampleParms(Object record, FinanceExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<Finance> selectByExampleWithBLOBs(FinanceExample arg0) {
        List<Finance> list = getSqlMapClientTemplate().queryForList("finance.selectByExample", arg0);
        return list;
	}

	public List<Finance> selectByExampleWithoutBLOBs(FinanceExample arg0) {
        List<Finance> list = getSqlMapClientTemplate().queryForList("finance.selectByExample", arg0);
        return list;
	}

	public int updateByExampleWithBLOBs(Finance arg0, FinanceExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(Finance arg0, FinanceExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(Finance arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(Finance arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}