package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.HighQualityProject;
import com.meidusa.demo.dal.model.HighQualityProjectExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class HighQualityProjectDAOImpl extends SqlMapClientDaoSupport implements HighQualityProjectDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public HighQualityProjectDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int countByExample(HighQualityProjectExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("highqualityproject.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int deleteByExample(HighQualityProjectExample example) {
        int rows = getSqlMapClientTemplate().delete("highqualityproject.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        HighQualityProject key = new HighQualityProject();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("highqualityproject.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public void insert(HighQualityProject record) {
        getSqlMapClientTemplate().insert("highqualityproject.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public void insertSelective(HighQualityProject record) {
        getSqlMapClientTemplate().insert("highqualityproject.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<HighQualityProject> selectByExample(HighQualityProjectExample example) {
        List<HighQualityProject> list = getSqlMapClientTemplate().queryForList("highqualityproject.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public HighQualityProject selectByPrimaryKey(String id) {
        HighQualityProject key = new HighQualityProject();
        key.setId(id);
        HighQualityProject record = (HighQualityProject) getSqlMapClientTemplate().queryForObject("highqualityproject.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByExampleSelective(HighQualityProject record, HighQualityProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("highqualityproject.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByExample(HighQualityProject record, HighQualityProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("highqualityproject.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByPrimaryKeySelective(HighQualityProject record) {
        int rows = getSqlMapClientTemplate().update("highqualityproject.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByPrimaryKey(HighQualityProject record) {
        int rows = getSqlMapClientTemplate().update("highqualityproject.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table highqualityproject
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    protected static class UpdateByExampleParms extends HighQualityProjectExample {
        private Object record;

        public UpdateByExampleParms(Object record, HighQualityProjectExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<HighQualityProject> selectByExampleWithBLOBs(
			HighQualityProjectExample example) {
        List<HighQualityProject> list = getSqlMapClientTemplate().queryForList("highqualityproject.selectByExample", example);
        return list;
	}

	@Override
	public List<HighQualityProject> selectByExampleWithoutBLOBs(
			HighQualityProjectExample example) {
        List<HighQualityProject> list = getSqlMapClientTemplate().queryForList("highqualityproject.selectByExample", example);
        return list;
	}

	@Override
	public int updateByExampleWithBLOBs(HighQualityProject arg0,
			HighQualityProjectExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByExampleWithoutBLOBs(HighQualityProject arg0,
			HighQualityProjectExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithBLOBs(HighQualityProject arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithoutBLOBs(HighQualityProject arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}