package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.IntegrityInfo;
import com.meidusa.demo.dal.model.IntegrityInfoExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface IntegrityInfoDAO extends AbstractDAO<IntegrityInfo, IntegrityInfoExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(IntegrityInfoExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(IntegrityInfoExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(IntegrityInfo record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(IntegrityInfo record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<IntegrityInfo> selectByExample(IntegrityInfoExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    IntegrityInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(IntegrityInfo record, IntegrityInfoExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExample(IntegrityInfo record, IntegrityInfoExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(IntegrityInfo record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKey(IntegrityInfo record);
}