package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.IntegrityInfo;
import com.meidusa.demo.dal.model.IntegrityInfoExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class IntegrityInfoDAOImpl extends SqlMapClientDaoSupport implements IntegrityInfoDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public IntegrityInfoDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(IntegrityInfoExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("integrityinfo.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(IntegrityInfoExample example) {
        int rows = getSqlMapClientTemplate().delete("integrityinfo.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        IntegrityInfo key = new IntegrityInfo();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("integrityinfo.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(IntegrityInfo record) {
        getSqlMapClientTemplate().insert("integrityinfo.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(IntegrityInfo record) {
        getSqlMapClientTemplate().insert("integrityinfo.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<IntegrityInfo> selectByExample(IntegrityInfoExample example) {
        List<IntegrityInfo> list = getSqlMapClientTemplate().queryForList("integrityinfo.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public IntegrityInfo selectByPrimaryKey(String id) {
        IntegrityInfo key = new IntegrityInfo();
        key.setId(id);
        IntegrityInfo record = (IntegrityInfo) getSqlMapClientTemplate().queryForObject("integrityinfo.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(IntegrityInfo record, IntegrityInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("integrityinfo.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(IntegrityInfo record, IntegrityInfoExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("integrityinfo.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(IntegrityInfo record) {
        int rows = getSqlMapClientTemplate().update("integrityinfo.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(IntegrityInfo record) {
        int rows = getSqlMapClientTemplate().update("integrityinfo.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table integrityinfo
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends IntegrityInfoExample {
        private Object record;

        public UpdateByExampleParms(Object record, IntegrityInfoExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<IntegrityInfo> selectByExampleWithBLOBs(
			IntegrityInfoExample arg0) {
        List<IntegrityInfo> list = getSqlMapClientTemplate().queryForList("integrityinfo.selectByExample", arg0);
        return list;
	}

	public List<IntegrityInfo> selectByExampleWithoutBLOBs(
			IntegrityInfoExample arg0) {
        List<IntegrityInfo> list = getSqlMapClientTemplate().queryForList("integrityinfo.selectByExample", arg0);
        return list;
	}

	public int updateByExampleWithBLOBs(IntegrityInfo arg0,
			IntegrityInfoExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(IntegrityInfo arg0,
			IntegrityInfoExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(IntegrityInfo arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(IntegrityInfo arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}