package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Litigation;
import com.meidusa.demo.dal.model.LitigationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class LitigationDAOImpl extends SqlMapClientDaoSupport implements LitigationDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public LitigationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(LitigationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("litigation.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(LitigationExample example) {
        int rows = getSqlMapClientTemplate().delete("litigation.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        Litigation key = new Litigation();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("litigation.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(Litigation record) {
        getSqlMapClientTemplate().insert("litigation.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(Litigation record) {
        getSqlMapClientTemplate().insert("litigation.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Litigation> selectByExampleWithBLOBs(LitigationExample example) {
        List<Litigation> list = getSqlMapClientTemplate().queryForList("litigation.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Litigation> selectByExampleWithoutBLOBs(LitigationExample example) {
        List<Litigation> list = getSqlMapClientTemplate().queryForList("litigation.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public Litigation selectByPrimaryKey(String id) {
        Litigation key = new Litigation();
        key.setId(id);
        Litigation record = (Litigation) getSqlMapClientTemplate().queryForObject("litigation.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(Litigation record, LitigationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("litigation.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleWithBLOBs(Litigation record, LitigationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("litigation.updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleWithoutBLOBs(Litigation record, LitigationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("litigation.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(Litigation record) {
        int rows = getSqlMapClientTemplate().update("litigation.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeyWithBLOBs(Litigation record) {
        int rows = getSqlMapClientTemplate().update("litigation.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeyWithoutBLOBs(Litigation record) {
        int rows = getSqlMapClientTemplate().update("litigation.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends LitigationExample {
        private Object record;

        public UpdateByExampleParms(Object record, LitigationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }
}