package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Litigation;
import com.meidusa.demo.dal.model.LitigationExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface LitigationDAO extends AbstractDAO<Litigation, LitigationExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(Litigation record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(Litigation record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<Litigation> selectByExampleWithBLOBs(LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<Litigation> selectByExampleWithoutBLOBs(LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    Litigation selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(Litigation record, LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleWithBLOBs(Litigation record, LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleWithoutBLOBs(Litigation record, LitigationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(Litigation record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(Litigation record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table litigation
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(Litigation record);
}