package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Notification;
import com.meidusa.demo.dal.model.NotificationExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface NotificationDAO extends AbstractDAO<Notification, NotificationExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int countByExample(NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int deleteByExample(NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    void insert(Notification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    void insertSelective(Notification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    List<Notification> selectByExampleWithBLOBs(NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    List<Notification> selectByExampleWithoutBLOBs(NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    Notification selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int updateByExampleSelective(Notification record, NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int updateByExampleWithBLOBs(Notification record, NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int updateByExampleWithoutBLOBs(Notification record, NotificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int updateByPrimaryKeySelective(Notification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(Notification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table notification
     *
     * @ibatorgenerated Sun Apr 25 12:40:10 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(Notification record);
}