package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Post;
import com.meidusa.demo.dal.model.PostExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class PostDAOImpl extends SqlMapClientDaoSupport implements PostDAO {

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public PostDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int countByExample(PostExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"post.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int deleteByExample(PostExample example) {
		int rows = getSqlMapClientTemplate().delete("post.deleteByExample",
				example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		Post key = new Post();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete("post.deleteByPrimaryKey",
				key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public void insert(Post record) {
		getSqlMapClientTemplate().insert("post.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public void insertSelective(Post record) {
		getSqlMapClientTemplate().insert("post.insertSelective", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Post> selectByExampleWithBLOBs(PostExample example) {
		List<Post> list = getSqlMapClientTemplate().queryForList(
				"post.selectByExampleWithBLOBs", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<Post> selectByExampleWithoutBLOBs(PostExample example) {
		List<Post> list = getSqlMapClientTemplate().queryForList(
				"post.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public Post selectByPrimaryKey(String id) {
		Post key = new Post();
		key.setId(id);
		Post record = (Post) getSqlMapClientTemplate().queryForObject(
				"post.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByExampleSelective(Post record, PostExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"post.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByExampleWithBLOBs(Post record, PostExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"post.updateByExampleWithBLOBs", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByExampleWithoutBLOBs(Post record, PostExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update("post.updateByExample",
				parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByPrimaryKeySelective(Post record) {
		int rows = getSqlMapClientTemplate().update(
				"post.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByPrimaryKeyWithBLOBs(Post record) {
		int rows = getSqlMapClientTemplate().update(
				"post.updateByPrimaryKeyWithBLOBs", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	public int updateByPrimaryKeyWithoutBLOBs(Post record) {
		int rows = getSqlMapClientTemplate().update("post.updateByPrimaryKey",
				record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS Ibator. This class corresponds to the database table post
	 * @ibatorgenerated  Sat Apr 24 14:06:07 CST 2010
	 */
	protected static class UpdateByExampleParms extends PostExample {
		private Object record;

		public UpdateByExampleParms(Object record, PostExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}
}