package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Product;
import com.meidusa.demo.dal.model.ProductExample;
import com.meidusa.demo.dal.model.ProductWithBLOBs;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProductDAOImpl extends SqlMapClientDaoSupport implements ProductDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public ProductDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int countByExample(ProductExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("product.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByExample(ProductExample example) {
        int rows = getSqlMapClientTemplate().delete("product.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        Product key = new Product();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("product.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insert(ProductWithBLOBs record) {
        getSqlMapClientTemplate().insert("product.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public void insertSelective(ProductWithBLOBs record) {
        getSqlMapClientTemplate().insert("product.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Product> selectByExampleWithBLOBs(ProductExample example) {
        List<Product> list = getSqlMapClientTemplate().queryForList("product.selectByExampleWithBLOBs", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Product> selectByExampleWithoutBLOBs(ProductExample example) {
        List<Product> list = getSqlMapClientTemplate().queryForList("product.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public ProductWithBLOBs selectByPrimaryKey(String id) {
        Product key = new Product();
        key.setId(id);
        ProductWithBLOBs record = (ProductWithBLOBs) getSqlMapClientTemplate().queryForObject("product.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExampleSelective(ProductWithBLOBs record, ProductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("product.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(ProductWithBLOBs record, ProductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("product.updateByExampleWithBLOBs", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByExample(Product record, ProductExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("product.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKeySelective(ProductWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("product.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(ProductWithBLOBs record) {
        int rows = getSqlMapClientTemplate().update("product.updateByPrimaryKeyWithBLOBs", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    public int updateByPrimaryKey(Product record) {
        int rows = getSqlMapClientTemplate().update("product.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table product
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    protected static class UpdateByExampleParms extends ProductExample {
        private Object record;

        public UpdateByExampleParms(Object record, ProductExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public void insert(Product arg0) {
		// TODO Auto-generated method stub
		
	}

	public void insertSelective(Product arg0) {
		// TODO Auto-generated method stub
		
	}

	public int updateByExampleSelective(Product arg0, ProductExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithBLOBs(Product arg0, ProductExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(Product arg0, ProductExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeySelective(Product arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(Product arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(Product arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}