package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Project;
import com.meidusa.demo.dal.model.ProjectExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface ProjectDAO extends AbstractDAO<Project, ProjectExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int countByExample(ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByExample(ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insert(Project record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    void insertSelective(Project record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<Project> selectByExampleWithBLOBs(ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    List<Project> selectByExampleWithoutBLOBs(ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    Project selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleSelective(Project record, ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleWithBLOBs(Project record, ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByExampleWithoutBLOBs(Project record, ProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeySelective(Project record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(Project record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table project
     *
     * @ibatorgenerated Tue May 04 11:41:32 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(Project record);
}