package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.ProjectStand;
import com.meidusa.demo.dal.model.ProjectStandExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface ProjectStandDAO extends AbstractDAO<ProjectStand, ProjectStandExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int countByExample(ProjectStandExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int deleteByExample(ProjectStandExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    void insert(ProjectStand record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    void insertSelective(ProjectStand record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    List<ProjectStand> selectByExample(ProjectStandExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    ProjectStand selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int updateByExampleSelective(ProjectStand record, ProjectStandExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int updateByExample(ProjectStand record, ProjectStandExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int updateByPrimaryKeySelective(ProjectStand record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    int updateByPrimaryKey(ProjectStand record);
}