package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.ProjectStand;
import com.meidusa.demo.dal.model.ProjectStandExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class ProjectStandDAOImpl extends SqlMapClientDaoSupport implements ProjectStandDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public ProjectStandDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int countByExample(ProjectStandExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("projectstand.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int deleteByExample(ProjectStandExample example) {
        int rows = getSqlMapClientTemplate().delete("projectstand.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        ProjectStand key = new ProjectStand();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("projectstand.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public void insert(ProjectStand record) {
        getSqlMapClientTemplate().insert("projectstand.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public void insertSelective(ProjectStand record) {
        getSqlMapClientTemplate().insert("projectstand.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<ProjectStand> selectByExample(ProjectStandExample example) {
        List<ProjectStand> list = getSqlMapClientTemplate().queryForList("projectstand.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public ProjectStand selectByPrimaryKey(String id) {
        ProjectStand key = new ProjectStand();
        key.setId(id);
        ProjectStand record = (ProjectStand) getSqlMapClientTemplate().queryForObject("projectstand.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByExampleSelective(ProjectStand record, ProjectStandExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("projectstand.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByExample(ProjectStand record, ProjectStandExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("projectstand.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByPrimaryKeySelective(ProjectStand record) {
        int rows = getSqlMapClientTemplate().update("projectstand.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    public int updateByPrimaryKey(ProjectStand record) {
        int rows = getSqlMapClientTemplate().update("projectstand.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table projectstand
     *
     * @ibatorgenerated Fri Jul 12 23:54:18 CST 2013
     */
    protected static class UpdateByExampleParms extends ProjectStandExample {
        private Object record;

        public UpdateByExampleParms(Object record, ProjectStandExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<ProjectStand> selectByExampleWithBLOBs(ProjectStandExample example) {
        List<ProjectStand> list = getSqlMapClientTemplate().queryForList("projectstand.selectByExample", example);
        return list;
	}

	@Override
	public List<ProjectStand> selectByExampleWithoutBLOBs(
			ProjectStandExample example) {
        List<ProjectStand> list = getSqlMapClientTemplate().queryForList("projectstand.selectByExample", example);
        return list;
	}

	@Override
	public int updateByExampleWithBLOBs(ProjectStand arg0,
			ProjectStandExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByExampleWithoutBLOBs(ProjectStand arg0,
			ProjectStandExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithBLOBs(ProjectStand arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithoutBLOBs(ProjectStand arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}