package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Qualification;
import com.meidusa.demo.dal.model.QualificationExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface QualificationDAO extends AbstractDAO<Qualification, QualificationExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int countByExample(QualificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int deleteByExample(QualificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    void insert(Qualification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    void insertSelective(Qualification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    List<Qualification> selectByExample(QualificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    Qualification selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int updateByExampleSelective(Qualification record, QualificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int updateByExample(Qualification record, QualificationExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int updateByPrimaryKeySelective(Qualification record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    int updateByPrimaryKey(Qualification record);
}