package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Qualification;
import com.meidusa.demo.dal.model.QualificationExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class QualificationDAOImpl extends SqlMapClientDaoSupport implements QualificationDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public QualificationDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int countByExample(QualificationExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("qualification.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int deleteByExample(QualificationExample example) {
        int rows = getSqlMapClientTemplate().delete("qualification.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int deleteByPrimaryKey(String id) {
        Qualification key = new Qualification();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("qualification.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public void insert(Qualification record) {
        getSqlMapClientTemplate().insert("qualification.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public void insertSelective(Qualification record) {
        getSqlMapClientTemplate().insert("qualification.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    @SuppressWarnings("unchecked")
    public List<Qualification> selectByExample(QualificationExample example) {
        List<Qualification> list = getSqlMapClientTemplate().queryForList("qualification.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public Qualification selectByPrimaryKey(String id) {
        Qualification key = new Qualification();
        key.setId(id);
        Qualification record = (Qualification) getSqlMapClientTemplate().queryForObject("qualification.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int updateByExampleSelective(Qualification record, QualificationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qualification.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int updateByExample(Qualification record, QualificationExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("qualification.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int updateByPrimaryKeySelective(Qualification record) {
        int rows = getSqlMapClientTemplate().update("qualification.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    public int updateByPrimaryKey(Qualification record) {
        int rows = getSqlMapClientTemplate().update("qualification.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table qualification
     *
     * @ibatorgenerated Thu May 06 20:48:27 CST 2010
     */
    protected static class UpdateByExampleParms extends QualificationExample {
        private Object record;

        public UpdateByExampleParms(Object record, QualificationExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	public List<Qualification> selectByExampleWithBLOBs(
			QualificationExample paramK) {
        List<Qualification> list = getSqlMapClientTemplate().queryForList("qualification.selectByExample", paramK);
        return list;
	}

	public List<Qualification> selectByExampleWithoutBLOBs(
			QualificationExample paramK) {
        List<Qualification> list = getSqlMapClientTemplate().queryForList("qualification.selectByExample", paramK);
        return list;
	}

	public int updateByExampleWithBLOBs(Qualification paramT,
			QualificationExample paramK) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(Qualification paramT,
			QualificationExample paramK) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(Qualification paramT) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(Qualification paramT) {
		// TODO Auto-generated method stub
		return 0;
	}
}