package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.SelfCompleteProject;
import com.meidusa.demo.dal.model.SelfCompleteProjectExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface SelfCompleteProjectDAO extends AbstractDAO<SelfCompleteProject, SelfCompleteProjectExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int countByExample(SelfCompleteProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int deleteByExample(SelfCompleteProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    void insert(SelfCompleteProject record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    void insertSelective(SelfCompleteProject record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    List<SelfCompleteProject> selectByExample(SelfCompleteProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    SelfCompleteProject selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int updateByExampleSelective(SelfCompleteProject record, SelfCompleteProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int updateByExample(SelfCompleteProject record, SelfCompleteProjectExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int updateByPrimaryKeySelective(SelfCompleteProject record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    int updateByPrimaryKey(SelfCompleteProject record);
}