package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.SelfEnterprise;
import com.meidusa.demo.dal.model.SelfEnterpriseExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface SelfEnterpriseDAO extends AbstractDAO<SelfEnterprise, SelfEnterpriseExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int countByExample(SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int deleteByExample(SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    void insert(SelfEnterprise record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    void insertSelective(SelfEnterprise record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    List<SelfEnterprise> selectByExampleWithBLOBs(SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    List<SelfEnterprise> selectByExampleWithoutBLOBs(SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    SelfEnterprise selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int updateByExampleSelective(SelfEnterprise record, SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int updateByExampleWithBLOBs(SelfEnterprise record, SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int updateByExampleWithoutBLOBs(SelfEnterprise record, SelfEnterpriseExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int updateByPrimaryKeySelective(SelfEnterprise record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int updateByPrimaryKeyWithBLOBs(SelfEnterprise record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfenterprise
     *
     * @ibatorgenerated Thu Jun 13 22:12:42 CST 2013
     */
    int updateByPrimaryKeyWithoutBLOBs(SelfEnterprise record);
}