package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.SelfCompleteProject;
import com.meidusa.demo.dal.model.SelfCompleteProjectExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SelfCompleteProjectDAOImpl extends SqlMapClientDaoSupport implements SelfCompleteProjectDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public SelfCompleteProjectDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int countByExample(SelfCompleteProjectExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("selfcompleteproject.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int deleteByExample(SelfCompleteProjectExample example) {
        int rows = getSqlMapClientTemplate().delete("selfcompleteproject.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        SelfCompleteProject key = new SelfCompleteProject();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("selfcompleteproject.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public void insert(SelfCompleteProject record) {
        getSqlMapClientTemplate().insert("selfcompleteproject.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public void insertSelective(SelfCompleteProject record) {
        getSqlMapClientTemplate().insert("selfcompleteproject.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<SelfCompleteProject> selectByExample(SelfCompleteProjectExample example) {
        List<SelfCompleteProject> list = getSqlMapClientTemplate().queryForList("selfcompleteproject.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public SelfCompleteProject selectByPrimaryKey(String id) {
        SelfCompleteProject key = new SelfCompleteProject();
        key.setId(id);
        SelfCompleteProject record = (SelfCompleteProject) getSqlMapClientTemplate().queryForObject("selfcompleteproject.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int updateByExampleSelective(SelfCompleteProject record, SelfCompleteProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("selfcompleteproject.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int updateByExample(SelfCompleteProject record, SelfCompleteProjectExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("selfcompleteproject.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int updateByPrimaryKeySelective(SelfCompleteProject record) {
        int rows = getSqlMapClientTemplate().update("selfcompleteproject.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    public int updateByPrimaryKey(SelfCompleteProject record) {
        int rows = getSqlMapClientTemplate().update("selfcompleteproject.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table selfcompleteproject
     *
     * @ibatorgenerated Tue Jun 18 16:39:21 CST 2013
     */
    protected static class UpdateByExampleParms extends SelfCompleteProjectExample {
        private Object record;

        public UpdateByExampleParms(Object record, SelfCompleteProjectExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<SelfCompleteProject> selectByExampleWithBLOBs(
			SelfCompleteProjectExample arg0) {
        List<SelfCompleteProject> list = getSqlMapClientTemplate().queryForList("selfcompleteproject.selectByExample", arg0);
        return list;
	}

	@Override
	public List<SelfCompleteProject> selectByExampleWithoutBLOBs(
			SelfCompleteProjectExample arg0) {
        List<SelfCompleteProject> list = getSqlMapClientTemplate().queryForList("selfcompleteproject.selectByExample", arg0);
        return list;
	}

	@Override
	public int updateByExampleWithBLOBs(SelfCompleteProject arg0,
			SelfCompleteProjectExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByExampleWithoutBLOBs(SelfCompleteProject arg0,
			SelfCompleteProjectExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithBLOBs(SelfCompleteProject arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithoutBLOBs(SelfCompleteProject arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}