package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.SelfCostEngineer;
import com.meidusa.demo.dal.model.SelfCostEngineerExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SelfCostEngineerDAOImpl extends SqlMapClientDaoSupport implements SelfCostEngineerDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public SelfCostEngineerDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int countByExample(SelfCostEngineerExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("selfcostengineer.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int deleteByExample(SelfCostEngineerExample example) {
        int rows = getSqlMapClientTemplate().delete("selfcostengineer.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        SelfCostEngineer key = new SelfCostEngineer();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("selfcostengineer.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void insert(SelfCostEngineer record) {
        getSqlMapClientTemplate().insert("selfcostengineer.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void insertSelective(SelfCostEngineer record) {
        getSqlMapClientTemplate().insert("selfcostengineer.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<SelfCostEngineer> selectByExample(SelfCostEngineerExample example) {
        List<SelfCostEngineer> list = getSqlMapClientTemplate().queryForList("selfcostengineer.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public SelfCostEngineer selectByPrimaryKey(String id) {
        SelfCostEngineer key = new SelfCostEngineer();
        key.setId(id);
        SelfCostEngineer record = (SelfCostEngineer) getSqlMapClientTemplate().queryForObject("selfcostengineer.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByExampleSelective(SelfCostEngineer record, SelfCostEngineerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("selfcostengineer.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByExample(SelfCostEngineer record, SelfCostEngineerExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("selfcostengineer.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByPrimaryKeySelective(SelfCostEngineer record) {
        int rows = getSqlMapClientTemplate().update("selfcostengineer.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByPrimaryKey(SelfCostEngineer record) {
        int rows = getSqlMapClientTemplate().update("selfcostengineer.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table selfcostengineer
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    protected static class UpdateByExampleParms extends SelfCostEngineerExample {
        private Object record;

        public UpdateByExampleParms(Object record, SelfCostEngineerExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<SelfCostEngineer> selectByExampleWithBLOBs(
			SelfCostEngineerExample arg0) {
        List<SelfCostEngineer> list = getSqlMapClientTemplate().queryForList("selfcostengineer.selectByExample", arg0);
        return list;
	}

	@Override
	public List<SelfCostEngineer> selectByExampleWithoutBLOBs(
			SelfCostEngineerExample arg0) {
        List<SelfCostEngineer> list = getSqlMapClientTemplate().queryForList("selfcostengineer.selectByExample", arg0);
        return list;
	}

	@Override
	public int updateByExampleWithBLOBs(SelfCostEngineer arg0,
			SelfCostEngineerExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByExampleWithoutBLOBs(SelfCostEngineer arg0,
			SelfCostEngineerExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithBLOBs(SelfCostEngineer arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithoutBLOBs(SelfCostEngineer arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}