package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.SelfTechPerson;
import com.meidusa.demo.dal.model.SelfTechPersonExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class SelfTechPersonDAOImpl extends SqlMapClientDaoSupport implements SelfTechPersonDAO {

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public SelfTechPersonDAOImpl() {
        super();
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int countByExample(SelfTechPersonExample example) {
        Integer count = (Integer)  getSqlMapClientTemplate().queryForObject("selftechperson.countByExample", example);
        return count;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int deleteByExample(SelfTechPersonExample example) {
        int rows = getSqlMapClientTemplate().delete("selftechperson.deleteByExample", example);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int deleteByPrimaryKey(String id) {
        SelfTechPerson key = new SelfTechPerson();
        key.setId(id);
        int rows = getSqlMapClientTemplate().delete("selftechperson.deleteByPrimaryKey", key);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void insert(SelfTechPerson record) {
        getSqlMapClientTemplate().insert("selftechperson.insert", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public void insertSelective(SelfTechPerson record) {
        getSqlMapClientTemplate().insert("selftechperson.insertSelective", record);
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    @SuppressWarnings("unchecked")
    public List<SelfTechPerson> selectByExample(SelfTechPersonExample example) {
        List<SelfTechPerson> list = getSqlMapClientTemplate().queryForList("selftechperson.selectByExample", example);
        return list;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public SelfTechPerson selectByPrimaryKey(String id) {
        SelfTechPerson key = new SelfTechPerson();
        key.setId(id);
        SelfTechPerson record = (SelfTechPerson) getSqlMapClientTemplate().queryForObject("selftechperson.selectByPrimaryKey", key);
        return record;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByExampleSelective(SelfTechPerson record, SelfTechPersonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("selftechperson.updateByExampleSelective", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByExample(SelfTechPerson record, SelfTechPersonExample example) {
        UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
        int rows = getSqlMapClientTemplate().update("selftechperson.updateByExample", parms);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByPrimaryKeySelective(SelfTechPerson record) {
        int rows = getSqlMapClientTemplate().update("selftechperson.updateByPrimaryKeySelective", record);
        return rows;
    }

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    public int updateByPrimaryKey(SelfTechPerson record) {
        int rows = getSqlMapClientTemplate().update("selftechperson.updateByPrimaryKey", record);
        return rows;
    }

    /**
     * This class was generated by Apache iBATIS Ibator.
     * This class corresponds to the database table selftechperson
     *
     * @ibatorgenerated Sun Jun 23 10:43:08 CST 2013
     */
    protected static class UpdateByExampleParms extends SelfTechPersonExample {
        private Object record;

        public UpdateByExampleParms(Object record, SelfTechPersonExample example) {
            super(example);
            this.record = record;
        }

        public Object getRecord() {
            return record;
        }
    }

	@Override
	public List<SelfTechPerson> selectByExampleWithBLOBs(
			SelfTechPersonExample arg0) {
        List<SelfTechPerson> list = getSqlMapClientTemplate().queryForList("selftechperson.selectByExample", arg0);
        return list;
	}

	@Override
	public List<SelfTechPerson> selectByExampleWithoutBLOBs(
			SelfTechPersonExample arg0) {
        List<SelfTechPerson> list = getSqlMapClientTemplate().queryForList("selftechperson.selectByExample", arg0);
        return list;
	}

	@Override
	public int updateByExampleWithBLOBs(SelfTechPerson arg0,
			SelfTechPersonExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByExampleWithoutBLOBs(SelfTechPerson arg0,
			SelfTechPersonExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithBLOBs(SelfTechPerson arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	@Override
	public int updateByPrimaryKeyWithoutBLOBs(SelfTechPerson arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}