package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.Training;
import com.meidusa.demo.dal.model.TrainingExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface TrainingDAO extends AbstractDAO<Training, TrainingExample> {
    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int countByExample(TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int deleteByExample(TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    void insert(Training record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    void insertSelective(Training record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    List<Training> selectByExampleWithBLOBs(TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    List<Training> selectByExampleWithoutBLOBs(TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    Training selectByPrimaryKey(String id);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByExampleSelective(Training record, TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByExampleWithBLOBs(Training record, TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByExampleWithoutBLOBs(Training record, TrainingExample example);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByPrimaryKeySelective(Training record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByPrimaryKeyWithBLOBs(Training record);

    /**
     * This method was generated by Apache iBATIS Ibator.
     * This method corresponds to the database table training
     *
     * @ibatorgenerated Sun Jun 20 22:44:16 CST 2010
     */
    int updateByPrimaryKeyWithoutBLOBs(Training record);
}