package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.UserPermission;
import com.meidusa.demo.dal.model.UserPermissionExample;
import com.meidusa.toolkit.dal.ibator.AbstractDAO;
import java.util.List;

public interface UserPermissionDAO extends AbstractDAO<UserPermission, UserPermissionExample> {

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int countByExample(UserPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int deleteByExample(UserPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int deleteByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	void insert(UserPermission record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	void insertSelective(UserPermission record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	List<UserPermission> selectByExample(UserPermissionExample example);
	
	List<UserPermission> selectByExampleWithoutBLOBs(UserPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	UserPermission selectByPrimaryKey(String id);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int updateByExampleSelective(UserPermission record,
			UserPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int updateByExample(UserPermission record, UserPermissionExample example);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int updateByPrimaryKeySelective(UserPermission record);

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	int updateByPrimaryKey(UserPermission record);
}