package com.meidusa.demo.dal;

import com.meidusa.demo.dal.model.UserPermission;
import com.meidusa.demo.dal.model.UserPermissionExample;
import java.util.List;
import org.springframework.orm.ibatis.support.SqlMapClientDaoSupport;

public class UserPermissionDAOImpl extends SqlMapClientDaoSupport implements UserPermissionDAO {

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public UserPermissionDAOImpl() {
		super();
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int countByExample(UserPermissionExample example) {
		Integer count = (Integer) getSqlMapClientTemplate().queryForObject(
				"userpermission.countByExample", example);
		return count;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int deleteByExample(UserPermissionExample example) {
		int rows = getSqlMapClientTemplate().delete(
				"userpermission.deleteByExample", example);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int deleteByPrimaryKey(String id) {
		UserPermission key = new UserPermission();
		key.setId(id);
		int rows = getSqlMapClientTemplate().delete(
				"userpermission.deleteByPrimaryKey", key);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public void insert(UserPermission record) {
		getSqlMapClientTemplate().insert("userpermission.insert", record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public void insertSelective(UserPermission record) {
		getSqlMapClientTemplate().insert("userpermission.insertSelective",
				record);
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	@SuppressWarnings("unchecked")
	public List<UserPermission> selectByExample(UserPermissionExample example) {
		List<UserPermission> list = getSqlMapClientTemplate().queryForList(
				"userpermission.selectByExample", example);
		return list;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public UserPermission selectByPrimaryKey(String id) {
		UserPermission key = new UserPermission();
		key.setId(id);
		UserPermission record = (UserPermission) getSqlMapClientTemplate()
				.queryForObject("userpermission.selectByPrimaryKey", key);
		return record;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int updateByExampleSelective(UserPermission record,
			UserPermissionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"userpermission.updateByExampleSelective", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int updateByExample(UserPermission record,
			UserPermissionExample example) {
		UpdateByExampleParms parms = new UpdateByExampleParms(record, example);
		int rows = getSqlMapClientTemplate().update(
				"userpermission.updateByExample", parms);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int updateByPrimaryKeySelective(UserPermission record) {
		int rows = getSqlMapClientTemplate().update(
				"userpermission.updateByPrimaryKeySelective", record);
		return rows;
	}

	/**
	 * This method was generated by Apache iBATIS Ibator. This method corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	public int updateByPrimaryKey(UserPermission record) {
		int rows = getSqlMapClientTemplate().update(
				"userpermission.updateByPrimaryKey", record);
		return rows;
	}

	/**
	 * This class was generated by Apache iBATIS Ibator. This class corresponds to the database table userpermission
	 * @ibatorgenerated  Sat May 01 09:15:06 CST 2010
	 */
	protected static class UpdateByExampleParms extends UserPermissionExample {
		private Object record;

		public UpdateByExampleParms(Object record, UserPermissionExample example) {
			super(example);
			this.record = record;
		}

		public Object getRecord() {
			return record;
		}
	}

	public List<UserPermission> selectByExampleWithBLOBs(
			UserPermissionExample arg0) {
		List<UserPermission> list = getSqlMapClientTemplate().queryForList(
				"userpermission.selectByExample", arg0);
		return list;
	}

	public List<UserPermission> selectByExampleWithoutBLOBs(
			UserPermissionExample arg0) {
		List<UserPermission> list = getSqlMapClientTemplate().queryForList(
				"userpermission.selectByExample", arg0);
		return list;
	}

	public int updateByExampleWithBLOBs(UserPermission arg0,
			UserPermissionExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByExampleWithoutBLOBs(UserPermission arg0,
			UserPermissionExample arg1) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithBLOBs(UserPermission arg0) {
		// TODO Auto-generated method stub
		return 0;
	}

	public int updateByPrimaryKeyWithoutBLOBs(UserPermission arg0) {
		// TODO Auto-generated method stub
		return 0;
	}
}